### ISSUE TITLE
Error Requesting Orgs from Discovery Server, EnableRegionDisco is disabled

### ISSUE THREAD

**Issue by steffenhds** [MscrmTools/XrmToolBox#1038]
XRMtoolkit worked last week. Now getting this error shown below when using wizard and manual created connection strings.

Google search for "Enable Region Discovery Dynamics" had this link in the results
https://powerapps.microsoft.com/en-us/blog/deprecation-of-the-regional-discovery-service/

---
- Connection Controls Version: 1.2021.5.42
- XrmToolBox Version: 1.2021.5.47

===error log===
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 8:25:32 AM  Initialize CRM connection Started - AuthType: Office365
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	5/25/2021 8:25:32 AM  Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	5/25/2021 8:25:32 AM  DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm9.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 8:25:32 AM  DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm9.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 8:25:34 AM  DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm9.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:01.2207968
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 8:25:34 AM  DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 8:25:35 AM  DiscoverOrganizations - Authenticated via OnlineFederation. Auth Elapsed:00:00:01.0800309
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 8:25:35 AM  DiscoverOrganizations - service proxy created - total create duration: 00:00:02.3090248
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 8:25:35 AM  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 8:25:35 AM  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Source	: Not Provided
Method	: Not Provided
Date	: 5/25/2021
Time	: 8:25:35 AM
Error	: ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 8:25:35 AM  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 5/25/2021
Time	: 8:25:35 AM
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 8:25:35 AM  Unable to connect to CRM: FCB 'EnableRegionalDisco' is disabled
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 5/25/2021
Time	: 8:25:35 AM
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 8:25:35 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 8:25:35 AM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 5/25/2021
Time	: 8:25:35 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Comment by steffenhds** [comment]
Sorry duplicate issue. Closing mine.
