### ISSUE TITLE
[BUG] XrmToolBox fails to load because of firewall.

### ISSUE THREAD

**Issue by BetimBeja** [MscrmTools/XrmToolBox#1042]
**Describe the bug**
XrmToolBox fails to load.

**To Reproduce**
Open XrmToolBox in a firewalled machine.

**Expected behavior**
XrmToolBox should open in a firewalled machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/11160171/120162032-46466200-c1f8-11eb-824f-80678aa6304e.png)
![image](https://user-images.githubusercontent.com/11160171/120162078-52322400-c1f8-11eb-85ad-584c809da8ed.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2021.5.47
 - McTools.Xrm.Connection Version: 1.2021.5.42

**Additional context**
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 152.199.23.209:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2021.5.47
    Win32 Version: 1.2021.5.47
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2021.5.47
    Win32 Version: 1.2021.5.47
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7601.24479
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.IdentityModel.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2021.5.47
    Win32 Version: 1.2021.5.47
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Common
    Assembly Version: 5.9.1.11
    Win32 Version: 5.9.1.11
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/NuGet.Common.DLL
----------------------------------------
NuGet.Packaging
    Assembly Version: 5.9.1.11
    Win32 Version: 5.9.1.11
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/NuGet.Packaging.DLL
----------------------------------------
NuGet.Protocol
    Assembly Version: 5.9.1.11
    Win32 Version: 5.9.1.11
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/NuGet.Protocol.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2021.5.42
    Win32 Version: 1.2021.5.42
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2021.5.42
    Win32 Version: 1.2021.5.42
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.46.2641
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.46.2641
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.46.2641
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.88
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.88
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.Xrm.Tooling.Ui.Styles.DLL
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.88
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.Xrm.Tooling.CrmConnectControl.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 5.2.9.0
    Win32 Version: 5.2.9.0
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
ScintillaNET
    Assembly Version: 3.6.3.0
    Win32 Version: 3.6.3.0
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/ScintillaNET.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AlbanianXrm.EarlyBound
    Assembly Version: 1.2020.5.1
    Win32 Version: 1.2020.05.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ALBANIANXRM.EARLYBOUND.DLL
----------------------------------------
AlbanianXrm.SolutionPackager
    Assembly Version: 1.2020.12.8
    Win32 Version: 1.2020.12.8
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ALBANIANXRM.SOLUTIONPACKAGER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2021.5.19
    Win32 Version: 1.2021.5.19
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2019.11.4
    Win32 Version: 1.2019.11.4
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly Version: 3.1.443.1
    Win32 Version: 3.1.443.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2021.2.4
    Win32 Version: 1.2021.2.4
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.AttributesFactory
    Assembly Version: 1.2021.5.8
    Win32 Version: 1.2021.5.8
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.ATTRIBUTESFACTORY.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2020.11.11
    Win32 Version: 1.2020.11.11
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2018.7.2
    Win32 Version: 1.2018.7.2
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2019.11.3
    Win32 Version: 1.2019.11.3
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2019.5.3
    Win32 Version: 1.2019.5.3
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeNamingChecker
    Assembly Version: 1.2020.6.0
    Win32 Version: 1.2020.6.0
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTENAMINGCHECKER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2018.9.11
    Win32 Version: 1.2018.9.11
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2019.11.2
    Win32 Version: 1.2019.11.2
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2020.2.4
    Win32 Version: 1.2020.2.4
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MscrmTools.EmailAnonymizer
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.EMAILANONYMIZER.DLL
----------------------------------------
MscrmTools.EnvironmentVariableManager
    Assembly Version: 1.2021.4.5
    Win32 Version: 1.2021.4.5
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ENVIRONMENTVARIABLEMANAGER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.12.3
    Win32 Version: 1.2017.12.3
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2021.2.11
    Win32 Version: 1.2021.2.11
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2021.5.15
    Win32 Version: 1.2021.5.15
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2021.4.4
    Win32 Version: 1.2021.4.4
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2021.1.15
    Win32 Version: 1.2021.1.15
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2021.4.27
    Win32 Version: 1.2021.4.27
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2018.6.23
    Win32 Version: 1.2018.6.23
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2020.2.12
    Win32 Version: 1.2020.2.12
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2021.5.5
    Win32 Version: 1.2021.5.5
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2021.4.13
    Win32 Version: 1.2021.4.13
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2021.4.6
    Win32 Version: 1.2021.4.6
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2020.4.2
    Win32 Version: 1.2020.4.2
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2021.2.2
    Win32 Version: 1.2021.2.2
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2021.4.15
    Win32 Version: 1.2021.4.15
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2020.4.13
    Win32 Version: 1.2020.4.13
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2020.7.5
    Win32 Version: 1.2020.7.5
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly Version: 2.2021.5.18
    Win32 Version: 2.2021.5.18
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
OrgSettings
    Assembly Version: 1.2020.315.1
    Win32 Version: 1.2020.315.001
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ORGSETTINGS.DLL
----------------------------------------
Rappen.XTB.FXB
    Assembly Version: 1.2021.4.4
    Win32 Version: 1.2021.04.004
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAPPEN.XTB.FXB.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration.Merged
    Assembly Version: 3.2021.4.1
    Win32 Version: 3.2021.04.001
    CodeBase: file:///C:/USERS/BETIM%20BEJA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.1.1.3
    Win32 Version: 4.6.26907.01
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/System.Net.Http.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
System.Drawing.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MetadataViewProxies_7afe38ee-2306-4ec1-9cc3-7ba123d888fb
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
NuGet.Configuration
    Assembly Version: 5.9.1.11
    Win32 Version: 5.9.1.11
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/NuGet.Configuration.DLL
----------------------------------------
NuGet.Versioning
    Assembly Version: 5.9.1.11
    Win32 Version: 5.9.1.11
    CodeBase: file:///C:/Users/Betim%20Beja/XrmToolbox/NuGet.Versioning.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by BetimBeja** [comment]
Updated to the latest version 1.2021.5.49 and the bug is resolved 😄
