### ISSUE TITLE
FCB 'EnableRegionalDisco' is disabled error message using Microsoft Login Control

### ISSUE THREAD

**Issue by biggo78** [MscrmTools/XrmToolBox#1045]
Hello,

I have created connections to CRM environments using Microsoft Login Control or the SDK Control which worked perfectly about 2 weeks ago. After a reboot, I tried to connect to my CRM environments using the same connections and it's failing.

The logged error is below and I can't seem to find anything about it. Do you have any idea what the issue might be.

My XRM Toolbox Version is 1.2021.5.49.

Source	: mscorlib
Method	: HandleReturnMessage
Date	: 6/3/2021
Time	: 4:02:17 PM
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryDiscoveryServer(ClientCredentials liveCreds, Uri discoServer)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

Thanks in advance.
G

**Comment by rodkings** [comment]
I'm having the same issue.
Seems to be related to this: https://powerapps.microsoft.com/en-us/blog/deprecation-of-the-regional-discovery-service/

**Comment by biggo78** [comment]
Thanks for your response.

It sounds like the code change needs to happen on the XRM Toolbox, right?

**Comment by rodkings** [comment]
@biggo78 looks like there is a workaround. check: https://github.com/MscrmTools/XrmToolBox/issues/1044

It worked for me.

**Comment by biggo78** [comment]
Thanks again for your help. Recreating it worked.

**Comment by sanket1828** [comment]
Hi I am using SDK, please advise that how I can use the global discovery service using SDK.

**Comment by MscrmTools** [comment]
With latest version of XrmToolBox, there shouldn't be any problem anymore

**Comment by sanket1828** [comment]
I am using microsft xrm sdk and using latest version. but still problem is there.

**Comment by MscrmTools** [comment]
Ok so nothing related to XrmToolBox as far as I understand

**Comment by sanket1828** [comment]
I need help on using microsft xrm sdk as I am using C# to get connected with dynamics. Please advise.

**Comment by MscrmTools** [comment]
So, this is a repository for XrmToolBox, not for helping people debugging their own code. There are lot of places where you can ask your question, like https://powerusers.microsoft.com/t5/Microsoft-Dataverse/bd-p/CDS_Apps
