### ISSUE TITLE
Connection issue v8.2

### ISSUE THREAD

**Issue by karpurshrikant** [MscrmTools/XrmToolBox#1059]
[Write your comment/feedback/issue here]

unable to connect with on premise ifd environment for CE version 8.2
getting the following error

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11-08-2021 09:19:19  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11-08-2021 09:19:19  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 11-08-2021
Time	: 09:19:19
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11-08-2021 09:19:30  Initialize CRM connection Started - AuthType: Claims
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11-08-2021 09:19:30  Discovery URI is = https://sts1.godrejinfotech.com:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11-08-2021 09:19:30  HomeRealm is = https://gitlcrm365.godrejinfotech.com/
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11-08-2021 09:19:30  DiscoverOrganizations - Initializing Discovery Server Object with https://sts1.godrejinfotech.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11-08-2021 09:19:30  DiscoverOrganizations - attempting to connect to CRM server @ https://sts1.godrejinfotech.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11-08-2021 09:19:30  Unable to login to Dynamics CRM, Error was : Metadata contains a reference that cannot be resolved: 'https://sts1.godrejinfotech.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Source	: System.ServiceModel
Method	: Retrieve
Date	: 11-08-2021
Time	: 09:19:30
Error	: Metadata contains a reference that cannot be resolved: 'https://sts1.godrejinfotech.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: FindServicePointHelper
Date	: 11-08-2021
Time	: 09:19:30
Error	: The ServicePointManager does not support proxies with the https scheme.
Stack Trace	: at System.Net.ServicePointManager.FindServicePointHelper(Uri address, Boolean isProxyServicePoint)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)
   at System.Net.HttpWebRequest.FindServicePoint(Boolean forceFind)
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11-08-2021 09:19:30  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11-08-2021 09:19:30  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 11-08-2021
Time	: 09:19:30
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

--
- Connection Controls Version: 1.2021.6.44
- XrmToolBox Version: 1.2021.6.51

**Comment by MscrmTools** [comment]
"Metadata contains a reference that cannot be resolved" error message means your computer cannot reach the mentioned url, so : https://sts1.godrejinfotech.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9

That seems "normal" to me since your url seem to be a mixed of ADFS server (sts1) and CRM path (/XRMServices/2011/Discovery.svc).

It looks very like a misconfiguration in your CRM/ADFS deployment
