### ISSUE TITLE
[BUG] Could not load file or assembly 'System.Net.Http'

### ISSUE THREAD

**Issue by alx-kpk** [MscrmTools/XrmToolBox#1070]
When executing XrmToolBox.exe following error appears:

![image](https://user-images.githubusercontent.com/35463768/134628639-79e79ddd-70d2-4019-a3d4-fa902031d996.png)

XrmToolBox Version: 1.2021.9.52
Windows Version: Windows Server 2016 Standard

**Comment by kadirkkkk** [comment]
When launching the xrmtoolbox a similar error came from a DLL file which exists in "C:\Users\<userName>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins"
what fix this error is to delete the "manifest.json" file in the Plugins folder. But it is disturbing to delete this file everytime i launch the app. 

Error Time: 2022-11-22 14:21:26.231
System.IO.FileNotFoundException
Could not load file or assembly 'colso.xrm.attrıbuteedıtor.dll' or one of its dependencies. The system cannot find the path specified.
mscorlib
at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

**Comment by kadirkkkk** [comment]
I need that tool :)

**Comment by MscrmTools** [comment]
I guess so... The issue is with the tool itself. I contacted the owner

**Comment by MscrmTools** [comment]
Same as #1172

**Comment by MscrmTools** [comment]
Fixed by the developer.
