### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kimberlyhouston** [MscrmTools/XrmToolBox#1150]
**Describe the bug**
I get an error message after installing latest version.  unable to open and use application.
I initially was prompted to update from older version and got the same error.  Then decided to uninstall and reinstall and the same error message persisted

**To Reproduce**
Installing or updating to XRM Toolbox version v1.2022.5.56

**Expected behavior**
Application should open and be able to use.

**Screenshots**
![image](https://user-images.githubusercontent.com/30115522/171881604-1ae90215-0479-4876-9d21-bcb559246ef8.png)

Error Time: 2022-06-03 10:08:18.065
System.AggregateException
One or more errors occurred.
System.Core
at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.CreateManifest(IReadOnlyCollection`1 composition, DirectoryCatalog catalogue)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

**Desktop (please complete the following information):**
 - XrmToolbox Version v1.2022.5.56
 - Tool version v1.2022.5.56

**Additional context**

**Comment by MscrmTools** [comment]
There should be a manifest.json file in your Plugins folder. Can you try to delete it?
![image](https://user-images.githubusercontent.com/10774317/171882757-49bf9932-7920-4c8e-bd05-b82b09b26b1a.png)

**Comment by kimberlyhouston** [comment]
issue resolved
