### ISSUE TITLE
[BUG] - Replace/Delete attribute from view and form _error importing entities

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/XrmToolBox#1162]
**Describe the bug**
I'm getting this error when loading Entities

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
at System.Linq.Enumerable.First[TSource](IEnumerable1 source, Func2 predicate)
at ReplaceAttributeXmPlugin.ReplaceAttributeControl.b__21_1(RunWorkerCompletedEventArgs e)
at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.b__0(Object s, RunWorkerCompletedEventArgs e)
at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**To Reproduce**
Open Replace/Delete attribute from view and form tool. Click load entities

**Expected behavior**
The error message shows up

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version V1.2022.2.54
 - Tool version: 1.2020.1.3

**Additional context**

**Comment by MscrmTools** [comment]
@StephaneSeguin Can you precise what tool this issue is from?
