### ISSUE TITLE
After update, the APP doesnt work [BUG]

### ISSUE THREAD

**Issue by dantedantas** [MscrmTools/XrmToolBox#1168]
**After update, the APP doesnt work**
After update, the APP doesnt open and show an error. Is it possible to download the old version again?

![image](https://user-images.githubusercontent.com/10854571/190137712-925d5f21-4d56-418a-b264-8b2b9de18f1c.png)

![image](https://user-images.githubusercontent.com/10854571/190138187-d001217f-73aa-47f6-803f-fdbbba9f0c9e.png)

Error Time: 2022-09-14 13:03:52.262
System.BadImageFormatException
Could not load file or assembly 'CINTEROS.XRM.FETCHXMLBUILDER.DLL' or one of its dependencies. An attempt was made to load a program with an incorrect format.
mscorlib
at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.<>c.<CreateManifest>b__4_2(String f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.CreateManifest(IReadOnlyCollection`1 composition, DirectoryCatalog catalogue)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

![image](https://user-images.githubusercontent.com/10854571/190138279-d647fd2e-f838-412a-869b-a2473935b053.png)

Please, could someone help me to solve this issue or tell me how to download the old version? Thank you!

Best regards,
Dante Dantas

**Comment by MscrmTools** [comment]
Hi @dantedantas, please remove the file mentioned in the error message from your Plugins folder and you should be good

**Comment by dantedantas** [comment]
Hi. Thank you for your feedback. Where could I found this folder? Is the installation folder? I dont see this file there.

**Comment by MscrmTools** [comment]
If you did not use a [custom folder for storage](https://www.xrmtoolbox.com/documentation/for-users/install-xrmtoolbox/), then it should be in C:\Users\<your_login>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins

**Comment by dantedantas** [comment]
Thank you very much, It works.
