### ISSUE TITLE
Object not set error in Script Finder

### ISSUE THREAD

**Issue by KP69** [MscrmTools/XrmToolBox#117]
Hello,
This is my first time using the XrmToolBox.  I was trying out Script Finder (Version: 1.2015.2.21).  When I clicked on Find Scripts I got "Object reference not set to an instance of an object" with following details..

System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.ScriptsFinder.ScriptsManager.LoadRibbonCommands(EntityMetadata emd) in c:\Users\userID.Company\Documents\Projects_Non_TFS\CRM Upgrade\XRMToolBox\XrmToolBox-master\Plugins\MsCrmTools.ScriptsFinder\ScriptsManager.cs:line 140
   at MsCrmTools.ScriptsFinder.ScriptsManager.Find() in c:\Users\userID.Company\Documents\Projects_Non_TFS\CRM Upgrade\XRMToolBox\XrmToolBox-master\Plugins\MsCrmTools.ScriptsFinder\ScriptsManager.cs:line 35
   at MsCrmTools.ScriptsFinder.ScriptsFinder.<FindScripts>b__0(DoWorkEventArgs e) in c:\Users\userID.Company\Documents\Projects_Non_TFS\CRM Upgrade\XRMToolBox\XrmToolBox-master\Plugins\MsCrmTools.ScriptsFinder\ScriptsFinder.cs:line 51
   at XrmToolBox.Worker.<>c__DisplayClass2.<WorkAsync>b__0(Object s, DoWorkEventArgs e) in c:\Users\userID.Company\Documents\Projects_Non_TFS\CRM Upgrade\XRMToolBox\XrmToolBox-master\XrmToolBox\Worker.cs:line 17
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

I'm connected to CRM 2011 (IFD).  

Thanks!

**Comment by MscrmTools** [comment]
Ok, it is due to the fact I don't check if the action is an URL action or a JavaScript action...

Let's fix this!

**Comment by KP69** [comment]
Wow! Thanks!
