### ISSUE TITLE
Cannot open latest release version on Windows 11 - could not load cinteros.xrm.fetchxmlbuilder.dll [BUG]

### ISSUE THREAD

**Issue by MrBenMyster** [MscrmTools/XrmToolBox#1195]
**To Reproduce**
1. Download the latest version and attempt to open XrmToolbox
2. Application crashes and does not open. Fails with this error:
Could not load file or assembly 'CINTEROS.XRM.FETCHXMLBUILDER.DLL' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Desktop info:**
 - XrmToolbox Version: 1.2022.11.59

**Additional context**
Full Stack Trace:
at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.<>c.<CreateManifest>b__4_2(String f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.CreateManifest(IReadOnlyCollection`1 composition, DirectoryCatalog catalogue)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

**Comment by MrBenMyster** [comment]
Was able to delete this assembly (CINTEROS.XRM.FETCHXMLBUILDER.DLL) in the **%appdata%\MscrmTools\XrmToolBox\Plugins** folder and then re-launch the application successfully.

**Comment by MscrmTools** [comment]
There can be some old files remaining in your XrmToolBox folder that might be not compatible with latest version. 
But I can see you fixed your issue by yourself
