### ISSUE TITLE
Connection crashes

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1228]
Direct after updating the connections: https://www.screencast.com/t/ProtaSxA0TjG

```

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at McTools.Xrm.Connection.WinForms.Forms.CompactConnectionSelector.cbbFiles_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at McTools.Xrm.Connection.WinForms.Forms.CompactConnectionSelector..ctor(IConnectionControlSettings settings)
   at McTools.Xrm.Connection.WinForms.FormHelper.AskForConnection(Object connectionParameter, Action`1 preConnectionRequestAction)
   at XrmToolBox.New.NewForm.<PluginsForm_OpenPluginRequested>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.1.63

**Comment by MscrmTools** [comment]
Already reported on issue #1228.
This is due to beta version of the controls.
I am releasing a new beta version

**Comment by rappen** [comment]
Also happens when I click the "Connect" button.
I can open it with the menu "Manage connections".

**Comment by rappen** [comment]
This is #1228...

**Comment by rappen** [comment]
Dup with #1227. Closing.
