### ISSUE TITLE
[BUG]XrmToolBox crashed when trying to debug a tool

### ISSUE THREAD

**Issue by ranistar** [MscrmTools/XrmToolBox#1271]
**Describe the bug**
XrmToolBox crashed when trying to debug a tool. It worked before, but after I upgraded the Xrm packages, somehow it crashed recently.

**To Reproduce**
Click the debug button in VS 2022, then error window occurs.

**Screenshots**
![image](https://github.com/MscrmTools/XrmToolBox/assets/14199700/4fb39bcc-83d6-4e61-826a-f961e3121bf0)

Error Time: 2023-07-20 17:03:40.842
System.IO.FileNotFoundException
Could not load file or assembly 'XrmToolBox.PluginsStore, Version=1.2023.1.63, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
XrmToolBox
at XrmToolBox.Program.CopyUpdatedPlugins()
   at XrmToolBox.Program.Main(String[] args)

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2023.6.65
 - Tool version 1.2023.6.65

**Comment by ranistar** [comment]
After upgrading to 1.2023.7.65, issue fixed. Seems there is a missing dll in old package: "XrmToolBox.PluginsStore.dll"
