### ISSUE TITLE
Tools not loaded report doesn't specify what tool is the culprit [BUG]

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#1274]
**Describe the bug**
Restarted my computer, now when I go to open XTB, I get this error:
![image](https://github.com/MscrmTools/XrmToolBox/assets/9728423/ebee9f2f-244b-4d2d-bf42-d97bd2ca2632)
followed by this one:
![image](https://github.com/MscrmTools/XrmToolBox/assets/9728423/ee0c694b-aa02-4bc1-bbb7-f438c4c4defe)
```
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm2..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)
```
Only thing I know of is that I had SQL4CDS scheduled to do an update on next XTB run, so I'm guessing that's the issue, but I'm guessing that there might be more information somewhere in the Stack trace (`XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)` maybe?) where the tool that is causing the error might be able to be caught and rethrown?

**To Reproduce**
I was able to fix the problem by deleting the Microsoft.PowerPlatform.Tooling.BatchedTelemetry form the plugins folder, so maybe add that file to that?  It might be that along with some combination of the the EBG V1 or V2 and SQL4CDS

**Expected behavior**
Better error?  Don't load dll dependencies that don't implement the XTB plugin?

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2023.6.65

**Comment by daryllabar** [comment]
@MscrmTools The error was caused by some extra dlls in the plugin directory.  Deleted them resolved the issue that caused me to created this.  Not sure if you want to change this to a feature request to add better logging, or not to load dlls that aren't plugins.  Looks like we will never get away from DLL Hell...

**Comment by MarkMpn** [comment]
I've done a bit more investigation on this - it looks like plugins that contain multiple dlls in the nuget package get those files duplicated when the tool is installed. For example, the latest version of SQL 4 CDS includes one main dll and several additional ones in a subfolder:

```
┝ MarkMpn.Sql4Cds.dll
└ MarkMpn.Sql4Cds
  ┝ MarkMpn.Sql4Cds.Controls.dll
  ┝ MarkMpn.Sql4Cds.Engine.dll
  ┝ MarkMpn.Sql4Cds.XTB.dll
  ┝ Microsoft.ApplicationInsights.dll
  ┝ Microsoft.SqlServer.TransactSql.ScriptDom.dll
  ┝ XPath2.dll
  └ XPath2.Extensions.dll
```

When the tool is installed it appears that all the files in the subfolder are also copied into the root of the Plugins folder:


```
┝ MarkMpn.Sql4Cds.dll
┝ MarkMpn.Sql4Cds.Controls.dll
┝ MarkMpn.Sql4Cds.Engine.dll
┝ MarkMpn.Sql4Cds.XTB.dll
┝ Microsoft.ApplicationInsights.dll
┝ Microsoft.SqlServer.TransactSql.ScriptDom.dll
┝ XPath2.dll
┝ XPath2.Extensions.dll
└ MarkMpn.Sql4Cds
  ┝ MarkMpn.Sql4Cds.Controls.dll
  ┝ MarkMpn.Sql4Cds.Engine.dll
  ┝ MarkMpn.Sql4Cds.XTB.dll
  ┝ Microsoft.ApplicationInsights.dll
  ┝ Microsoft.SqlServer.TransactSql.ScriptDom.dll
  ┝ XPath2.dll
  └ XPath2.Extensions.dll
```

Because these files are in the root of the plugin folder they get loaded automatically when XTB starts and scans the folder for plugins, so the code in the `AssemblyResolve` handler is not called because the assembly is already loaded.

I'm not sure if this is specific to how the SQL 4 CDS NuGet package is built or a bug with how the tool library is extracting the files from the package.

**Comment by MarkMpn** [comment]
Thanks - there may need to be some sort of cleanup process to remove non-plugin assemblies from the root folder to avoid versioning conflicts. If the new version only gets copied to the subfolder but older ones are in the root I believe it will try to use the old version and likely throw an exception about a version mismatch.

**Comment by bwmodular** [comment]
I'm experiencing something similar - I attempted to update SQL4CDS, the toolbox crashed, and now I can't start it again - I get this:

![Image](https://github.com/user-attachments/assets/24311f29-755d-42d9-9431-aa7fa16a25f9)

Any ideas what I need to do?

**Comment by bwmodular** [comment]
Amazing - thanks for the help Daryl, that's done it!
