### ISSUE TITLE
Reconnecting issue

### ISSUE THREAD

**Issue by Serjanya** [MscrmTools/XrmToolBox#1277]
I use XTB in conjunction with VPN, and sometimes I have to turn off VPN. After reconnecting, the connection in the utilities no longer works. Reconnecting to the organization through the "Connect" button at the top does not help either. Only restarting XTB and choosing a connection for the organization again helps.

What I see when reconnecting any organization:

![image](https://github.com/MscrmTools/XrmToolBox/assets/8789739/e6ce83e1-0d09-4954-82eb-4de163c42fdf)

```
************** Exception Text **************
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
```

---
- Deployment: OnPremise
- DB Version: 8.2.1.342
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.6.65

**Comment by MscrmTools** [comment]
Can you try to change this setting and see if it changes something when reconnecting?
![image](https://github.com/MscrmTools/XrmToolBox/assets/10774317/3a398f6b-2189-418c-86fb-4f9d89ef459f)

**Comment by Serjanya** [comment]
> Can you try to change this setting and see if it changes something when reconnecting? ![image](https://user-images.githubusercontent.com/10774317/265752836-3a398f6b-2189-418c-86fb-4f9d89ef459f.png)

Unfortuantly, it doesn't help. The same error
