### ISSUE TITLE
Bulk Data Updater - Error installing (Microsoft.PowerFx.Interpreter)

### ISSUE THREAD

**Issue by killerrin** [MscrmTools/XrmToolBox#1295]
@rappen I'm getting an error when attempting to install Bulk Data Updater on a fresh install. It looks like there might be an issue with the PowerFX dependencies

During the install of the tool, it'll just spam this message a couple dozen times. Then on restart of XrmToolbox it'll spam this error again until I go into the plugin folder and delete the tool manually

Here is all the errors I've managed to pull out.

> Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

![image](https://github.com/MscrmTools/XrmToolBox/assets/3269687/46587bb3-6a36-4cd5-92de-61e831b9a642)
![image](https://github.com/MscrmTools/XrmToolBox/assets/3269687/651adb03-3562-41aa-869f-e13635042073)

> at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm2..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

**Comment by MscrmTools** [comment]
Summoning @rappen, the author of the tool

**Comment by rappen** [comment]
Ok, I'm sorry for this inconvenience...
Can you try to download this file it is missing, unpack it, put it in the XrmToolBox folder, and try again?
https://1drv.ms/u/s!AjplCnpZdSjqn_EiNKACxQ11NZ3N7Q?e=lOhVj9

But it's strange... I have that file already in my folder, in a brand new installed XTB:

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/c9ffcc13-d0e3-4323-92cf-2608ecd4587a)

I see this file in version 7.0.22.51805, but your message says it needs version 6.*

I seem to have to say... "It works on my machine." 🙄

**Comment by killerrin** [comment]
Its odd because If I look at my install of XrmToolbox, I can see that it also came with the same version of the dll (7.0.22.51805)

Could the version mismatch be causing issues?

![image](https://github.com/MscrmTools/XrmToolBox/assets/3269687/aed6245a-9b2c-434f-b611-f5203ebc7167)

**Comment by rappen** [comment]
Maybe a stupid question - but which version of BDU are you using?

**Comment by killerrin** [comment]
The latest version, 1.2022.11.2

That said, I think I may have figured it out. I think one of the previous attempts to install it may have gotten corrupted somehow. Because I went in, deleted the metadata folder, plus the packages from the NugetPlugins and Plugins folders and then Toolbox finally took the install.

So it works now. Though I find it weird that a new install of the tool wouldn't have just overwritten these files anyhow. 🤔

**Comment by rappen** [comment]
Thanks for finding the solution.
Maybe time to bring back @MscrmTools now?

**Comment by MscrmTools** [comment]
New install won't clean the storage folder. It can add back missing file but cannot clean existing files. 
There was a bug in some previous version where additional files were stored in the wrong place.
That might explain (or not) the issue

**Comment by killerrin** [comment]
I was thinking more installing the Bulk Data Updater itself... Assuming that the issue was with what was stored within the Plugin/NugetPlugin folders, since I'd have thought those files would have been overridden when you tried to install/reinstall a tool. 

Though I guess if it was the Metadata folder screwing it up, then nothing could have prevented it
