### ISSUE TITLE
[BUG]Microsoft.Xrm.Tooling.Connector login 

### ISSUE THREAD

**Issue by julians1966** [MscrmTools/XrmToolBox#1305]
**Describe the bug**
Error connecting to Dataverse environment when generating early bound entities with Early Bound Generator by Daryl LaBar.
Note v1 not v2 of the tool

**To Reproduce**
Steps to reproduce the behavior
1. Launch Early Bound Generator by Daryl LaBar.
2. Click Create Entities.
3. In Microsoft Login control, select Office 365 and check Display list of available organizations and check Show Advanced
4. Enter email address and password
5. Error shown "An error occurred processing the login request"

**Expected behavior**
Connect to environment and retrieve metadata to generate early bound classes

**Log**
Source	: Microsoft.Xrm.Tooling.Connector
Method	: MoveNext
Date	: 12/6/2023
Time	: 6:25:49 AM
Error	: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.<QueryGlobalDiscovery>d__204.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryGlobalDiscovery(String authToken, Uri discoveryServiceUri, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.203.12.68
 - Tool version 1.023.12.1

**Comment by daryllabar** [comment]
This would be an issue with the EBG V1.  It creates it's own connection to CRM via the CrmSvcUtil.

**Comment by daryllabar** [comment]
I'm unable to transfer this over, can you recreate it in my repo: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

**Comment by julians1966** [comment]
Yes EBG V1
#460 raised
