### ISSUE TITLE
XrmToolbox - Not able to install any tool from Tool Library

### ISSUE THREAD

**Issue by GayathriTU123** [MscrmTools/XrmToolBox#1337]
**Describe the bug**
XrmToolbox - Not able to install any tool from Tool Library

**To Reproduce**
I have cleared the app cache as well from roaming folder, also I have even updated the Proxy setting to Browser

**Screenshots**
<img width="960" alt="Capture" src="https://github.com/MscrmTools/XrmToolBox/assets/170601773/0e4efe37-2381-493d-9d47-5d5a9dc382f4">
ng…]()

**Desktop (please complete the following information):**
 - XrmToolbox Version - XrmToolBox v1.2023.12.68

**Additional context**
Error Details 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending)
   at XrmToolBox.ToolLibrary.UserControls.ToolPackageCtrl.<GetVersions>b__15_1(Object s, RunWorkerCompletedEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4712.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2023.12.68
    Win32 Version: 1.2023.12.68
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/XrmToolBox.exe
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 7.1.17312.0
    Win32 Version: 7.01.17312.0
    CodeBase: file:///C:/Windows/System32/CrowdStrike.Sensor.ScriptControl17312.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2023.12.68
    Win32 Version: 1.2023.12.68
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4654.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7601.24479
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.IdentityModel.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
XrmToolBox.ToolLibrary
    Assembly Version: 1.2023.12.68
    Win32 Version: 1.2023.12.68
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/XrmToolBox.ToolLibrary.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2023.6.56
    Win32 Version: 1.2023.6.56
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2023.6.56
    Win32 Version: 1.2023.6.56
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.2.49.3165
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.2.49.665
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.2.49.3165
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.155
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.155
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Xrm.Tooling.Ui.Styles.DLL
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.155
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Xrm.Tooling.CrmConnectControl.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 5.3.0.0
    Win32 Version: 5.3.0.0
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
ScintillaNET
    Assembly Version: 3.6.3.0
    Win32 Version: 3.6.3.0
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/ScintillaNET.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1518.46
    Win32 Version: 1.0.1518.46
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1518.46
    Win32 Version: 1.0.1518.46
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4712.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/tugaya/Downloads/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2023.11.30
    Win32 Version: 1.2023.11.30
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2019.11.4
    Win32 Version: 1.2019.11.4
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2021.2.4
    Win32 Version: 1.2021.2.4
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.AttributesFactory
    Assembly Version: 1.2023.10.34
    Win32 Version: 1.2023.10.34
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.ATTRIBUTESFACTORY.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2022.12.12
    Win32 Version: 1.2022.12.12
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2023.11.7
    Win32 Version: 1.2023.11.7
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2019.11.3
    Win32 Version: 1.2019.11.3
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2022.10.4
    Win32 Version: 1.2022.10.4
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeNamingChecker
    Assembly Version: 1.2020.6.0
    Win32 Version: 1.2020.6.0
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTENAMINGCHECKER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2018.9.11
    Win32 Version: 1.2018.9.11
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2019.11.2
    Win32 Version: 1.2019.11.2
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.ComponentComparer
    Assembly Version: 1.2022.6.4
    Win32 Version: 1.2022.6.4
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.COMPONENTCOMPARER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2020.2.4
    Win32 Version: 1.2020.2.4
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MscrmTools.EmailAnonymizer
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.1
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.EMAILANONYMIZER.DLL
----------------------------------------
MscrmTools.EnvironmentProcessesComparer
    Assembly Version: 1.2021.12.2
    Win32 Version: 1.2021.12.2
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ENVIRONMENTPROCESSESCOMPARER.DLL
----------------------------------------
MscrmTools.EnvironmentVariableManager
    Assembly Version: 1.2023.1.10
    Win32 Version: 1.2022.1.10
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ENVIRONMENTVARIABLEMANAGER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2021.11.4
    Win32 Version: 1.2021.11.4
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2021.7.13
    Win32 Version: 1.2021.7.13
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2023.10.26
    Win32 Version: 1.2023.10.26
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2022.12.7
    Win32 Version: 1.2022.12.7
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PolymorphicLookupCreator
    Assembly Version: 1.2022.11.6
    Win32 Version: 1.2022.11.6
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.POLYMORPHICLOOKUPCREATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2023.10.18
    Win32 Version: 1.2023.10.18
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2022.11.33
    Win32 Version: 1.2022.11.33
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2018.6.23
    Win32 Version: 1.2018.6.23
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2023.7.18
    Win32 Version: 1.2023.7.18
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2022.11.9
    Win32 Version: 1.2022.11.9
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2021.9.14
    Win32 Version: 1.2021.9.14
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2023.2.16
    Win32 Version: 1.2023.2.16
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SolutionLayersExplorer
    Assembly Version: 1.2023.10.20
    Win32 Version: 1.2023.10.20
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONLAYERSEXPLORER.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2022.5.5
    Win32 Version: 1.2022.5.5
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2021.7.3
    Win32 Version: 1.2021.7.3
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2023.1.23
    Win32 Version: 1.2023.1.23
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2023.9.25
    Win32 Version: 1.2023.09.25
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MscrmTools.UserViewsDisplaySettings
    Assembly Version: 1.2022.4.2
    Win32 Version: 1.2022.4.2
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERVIEWSDISPLAYSETTINGS.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2023.10.14
    Win32 Version: 1.2023.10.14
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly Version: 2.2023.9.24
    Win32 Version: 2.2023.9.24
    CodeBase: file:///C:/USERS/TUGAYA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
MetadataViewProxies_6d645294-e109-40cf-b8c8-5134fd2e15fc
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4690.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by GayathriTU123** [comment]
@MscrmTools

**Comment by MscrmTools** [comment]
Can you explain when the error occurs? Is this when selecting a tool or when trying to install it?

**Comment by GayathriTU123** [comment]
@MscrmTools I happens when trying to select a tool from Tool Library
