### ISSUE TITLE
[BUG] Error when calling OnOutgoingMessage

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#1352]
I'm attempting to enable the EBG to use the IMessageBusHost, but when i make a call from the source plugin, I first get this error:

![image](https://github.com/user-attachments/assets/4a04c136-3926-4e2d-8dc8-df7a3456f112)

Which I then click OK to, and then I get this error:
![image](https://github.com/user-attachments/assets/c80c43bd-727b-4af3-a8a3-6bf10e102983)

And if I trigger the call a second time, I get this error:
![image](https://github.com/user-attachments/assets/f6328553-097c-477e-a31f-8bfc8a095f51)
with this exception details:

> System.ArgumentException: Invalid DockState: Content can not be showed as "Unknown" or "Hidden".
>    at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
>    at XrmToolBox.New.NewForm.MainForm_MessageBroker(Object sender, MessageBusEventArgs message)
>    at DLaB.VSSolutionAccelerator.VsSolutionAcceleratorPlugin.OpenEarlyBoundGeneratorWithSettings(String path)
>    at DLaB.VSSolutionAccelerator.VsSolutionAcceleratorPlugin.<Execute>b__16_0(BackgroundWorker w, DoWorkEventArgs e)
>    at DLaB.XrmToolBoxCommon.Extensions.<>c__DisplayClass14_0.<WithLogger>b__0(BackgroundWorker w, DoWorkEventArgs args)

**Comment by daryllabar** [comment]
Figured out that It's because I'm calling it from the WorkAsync thread.  Leaving this here for future people that experience the same thing.
