### ISSUE TITLE
[BUG]Can't connect to organization after latest update

### ISSUE THREAD

**Issue by jjkoran** [MscrmTools/XrmToolBox#1357]
**Describe the bug**
I have tried connecting multiple ways and keep getting the error message: I get the attached error message below:
![XRMToolBoxError](https://github.com/user-attachments/assets/dad81495-82fd-418e-a642-d59424fecd1a)

I have tried creating a new connection every which way and keep getting the same error. 

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
Can you show me the version number of assemblies (Settings > Assemblies)

**Comment by jjkoran** [comment]
I am connected now.  It appears it did not update the EXE to the latest version when I clicked update from the XRMToolBox.  I downloaded the latest version manually and it is now working.

**Comment by jjkoran** [comment]
I downloaded the latest version manually, and it started working.  I think the update updated the user data but not the EXE.  When I looked at the EXE version of my toolbox, it was still pointing to the previous version.

J. J. Koran
Director of Finance & Information Technology | Institute of Industrial and Systems Engineers
(770) 349-1111 | ***@***.******@***.***>
www.iise.org<http://www.iise.org/>

Call for Abstracts! Share your expertise with professionals and students at the Healthcare Systems Process Improvement Conference 2025, Feb. 19-21 in Atlanta. Submit your abstract by Sept. 27<https://www.iise.org/hspi> to be considered for an oral presentation, poster, or intensive session in the #HSPI2025 program.

**Comment by MscrmTools** [comment]
Ok it seems that people having issues are the ones who updated connection controls but not XrmToolBox (or XrmToolBox update fails for some reason I cannot explain).
Just update XrmToolBox manually and you should be fine

**Comment by magicalKhachapuri** [comment]
I also have the same problem, can't connect to the organization since the last update. Stack trace looks like this:

> Source	: Microsoft.Xrm.Tooling.Connector
Method	: MoveNext
Date	: 9/24/2024
Time	: 10:37:28 AM
Error	: Method not found: 'Void Microsoft.Xrm.Sdk.Discovery.OrganizationDetail.set_SchemaType(System.String)'.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.<QueryGlobalDiscovery>d__205.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryGlobalDiscovery(String authToken, Uri discoveryServiceUri, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)

@MscrmTools What do you mean by manual update ? Downloading new version from web page or downloading through XrmToolbox > Help > Check for update ?

**Comment by MscrmTools** [comment]
Manual means download from website.

Update from XrmToolBox itself should work too but it seems not for some people

**Comment by magicalKhachapuri** [comment]
Yes, updating through the tool doesn't work for me as well. Thanks.

**Comment by james-reinhardt** [comment]
Just commenting to say same issue here using update in XrmToolbox. 3 coworkers had same issue.
Will wait for a new update to show in the UI.

**Comment by JonMarr** [comment]
Works fine if you do a new install.

**Comment by pavanmanideep** [comment]
Yes, faced the same problem, fresh install resolved the issue.

**Comment by MscrmTools** [comment]
For all people having the issue. It seems the first update does not apply. Forcing an update again solves the issue
