### ISSUE TITLE
Cannot connect following latest updated.

### ISSUE THREAD

**Issue by rogerhillgsy** [MscrmTools/XrmToolBox#1360]
Updated just now to the latest version, and no longer able to connect to any CRM system.

This is the tail of my login_errorlog.log file.

Source	: System.ServiceModel
Method	: Retrieve
Date	: 24/09/2024
Time	: 12:54:08
Error	: Metadata contains a reference that cannot be resolved: 'https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9.2'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryDiscoveryServer(ClientCredentials liveCreds, Uri discoServer)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 24/09/2024
Time	: 12:54:08
Error	: The remote server returned an error: (404) Not Found.
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================

---
- Connection Controls Version: 1.2024.9.59
- XrmToolBox Version: 1.2023.12.68

**Comment by jrobidas** [comment]
Same error over here, I tried with a handful of environments on different servers and I get the same error everywhere.

**Comment by MscrmTools** [comment]
Your update of XrmToolBox certainly did not work as expected and you are still using previous version. Please try to update again and if it does not work, please download the update from XrmToolBox portal

**Comment by jrobidas** [comment]
> Your update of XrmToolBox certainly did not work as expected and you are still using previous version. Please try to update again and if it does not work, please download the update from XrmToolBox portal

Thanks a lot, I deleted the app and redownloaded and it works now. I suppose something funky happened when it tried to download and install the update.

**Comment by DMaxwell02** [comment]
Same here. Deleting the XrmToolBox folder and downloading and reinstalling it helped clear the connection issues.

**Comment by mscottsewell** [comment]
Yes - Same here - I reverted to the previous version and it had no trouble connecting.
