### ISSUE TITLE
reenter creedentials in each action

### ISSUE THREAD

**Issue by marcesepu** [MscrmTools/XrmToolBox#1363]
I've updated today, now I need to reenter my credentials when I do any action or open any plugin

---
- Connection Controls Version: 1.2024.9.59
- XrmToolBox Version: 1.2024.9.69

**Comment by MscrmTools** [comment]
Hi Marcelo, 
Can you confirm the update did succeed and you are using version 1.2024.9.69?

**Comment by chironh** [comment]
I'm experiencing the same issue. I have downloaded XrmToolbox from the website and I'm currently using 1.2024.9.69.
The authentication window keeps flashing, or is asking credentials multiple times, which is causing certain plugins just to crash.

I have it on multiple connections, even after recreating them.

**Comment by chironh** [comment]
To be more clear: creating the connection works just fine.

It's after using a plugin the authentication window starts flashing or is asking credentials, I guess after authentication fails multiple times, or happens too often?

**Comment by marcesepu** [comment]
> Hi Marcelo, Can you confirm the update did succeed and you are using version 1.2024.9.69?

yes, I'm using this version, now, I've donwload the XRMTOOLBOX from web, and reinstall manually, the error was fixed, the issue happen when you update xrmtoolbox from the app

**Comment by chironh** [comment]
Downloaded the XrmToolbox from the website, and connected to an environment. It again asks for credentials, and starts flashing. Sometimes it asks credentials again after a while, or says it can't login (I guess the authentication is being blocked because of all the attempts).

https://streamable.com/5lhvtv

**Comment by TheBrandt** [comment]
I'm experiencing a lot of problems as well. I'm getting more login popups, and something like the Plugin Trace Viewer just kinda dies after a load of login popups appearing and disappearing.

I fished this stacktrace from the connection logging that might be relevant:

````Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1-10-2024 15:07:16  Executed Command - RetrieveMultiple : RetrieveMultiple to CRM via IOrganizationService : RequestID=0718484d-2890-4d83-b952-3c7be85aeb34 : duration=00:00:01.1881862
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1-10-2024 15:07:18  Execute Command - RetrieveMultiple : RetrieveMultiple to CRM via IOrganizationService : RequestID=813d36fa-7c6c-469b-839a-a07743e747e2 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	1-10-2024 15:07:18  Error occurred in CrmServiceClientTokenCache.AfterAccessNotification(). 
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\redacted\AppData\Local\Temp\{c20debe7-6ef8-45ab-afa9-adce791845ef}' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache.AfterAccessNotification(TokenCacheNotificationArgs args)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	1-10-2024 15:07:18  Error occurred in CrmServiceClientTokenCache.AfterAccessNotification(). 
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\redacted\AppData\Local\Temp\{c20debe7-6ef8-45ab-afa9-adce791845ef}' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache.AfterAccessNotification(TokenCacheNotificationArgs args)
Source	: Not Provided
Method	: Not Provided
Date	: 1-10-2024
Time	: 15:07:18
Error	: Error occurred in CrmServiceClientTokenCache.AfterAccessNotification(). 
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\redacted\AppData\Local\Temp\{c20debe7-6ef8-45ab-afa9-adce791845ef}' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache.AfterAccessNotification(TokenCacheNotificationArgs args)
Stack Trace	: Not Provided
````

That folder does seem to exist in the specified location, it contains an "oauth-cache.txt" file.

**Comment by marcesepu** [comment]
> Downloaded the XrmToolbox from the website, and connected to an environment. It again asks for credentials, and starts flashing. Sometimes it asks credentials again after a while, or says it can't login (I guess the authentication is being blocked because of all the attempts).
> 
> https://streamable.com/5lhvtv

yes, the same error

**Comment by Djitea1** [comment]
I am experiencing the same issue. Currently I am experiencing it when using Data migration tool. Sign-in keeps popping up until it finally requires my intervention clicking Next and entering the password.

**Comment by guillaumeDMSFT** [comment]
I am experiencing the same issue when using Data migration plugin. Sign-in popups keep popping up until it finally requires my intervention clicking Next and entering the password. But it fails, too many authentication requestss.
Using version 1.2024.9.69.

When rolling back to v1.2023.10.67, issue is not met.

**Comment by MscrmTools** [comment]
Can you precise which kind of authentication method you are using? It seems to me that it occurs only with Microsoft Login Control method

**Comment by guillaumeDMSFT** [comment]
That's correct. Microsoft Login Method.

**Comment by MscrmTools** [comment]
This is the most complicated for me since I don't handle how it works, how it caches credentials, etc. As soon as you open Microsoft Login Control, my code is almost not involved anymore

**Comment by MscrmTools** [comment]
Yes, the version of Microsoft control changed. But as far as I can tell, nothing in my code has changed that could lead to this behavior

**Comment by Slowylowy** [comment]
Is there any new information or a work around for this issue? I'm still encountering the same problem, unfortunately.

**Comment by mhammons** [comment]
I am experiencing the exact same problem.

Using v1.2024.9.69

XMRToolBox connects fine to the environment. I am trying run Model-Apps Copier, which I use a LO, and it is popping up a login for every step and it is not accepting my correct username/pw.

![Image](https://github.com/user-attachments/assets/034beda7-a4da-457b-a8a9-800ddb80106e)

**Comment by chironh** [comment]
For people still struggling with this issue, I managed to fix it.

Because certain plugins wouldn't work anymore on the 2023 xrmtoolbox version because of missing assemblies, I was more or less forced to resolve the issue.

Like stated above and in different other topics, the issue is related to not having (or having broken - my best guess) access to a certain temp folder.

You can find the logs here:
C:\Users\\{user}\AppData\Roaming\MscrmTools\XrmToolBox\1.2025.10.74

Look for something like:
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\\{user}\AppData\Local\Temp\{0992d972-17fe-4dcd-bff1-bc1f8b04d7e7}' is denied.

Delete that specific folder, in my case "{0992d972-17fe-4dcd-bff1-bc1f8b04d7e7}".

After this it started working again.

**Comment by Slowylowy** [comment]
Thanks, chironh!
Deleted the whole Temp folder, but this solved the issue.

**Comment by chironh** [comment]
Update: the problem comes back after some time (maybe after a reboot?), but deleting the temp folder again fixes the problem once more. After this I can work all day without any issues.

Looks like access to that temp folder is only granted temporarily, or something like that?
