### ISSUE TITLE
Connections stoppped working

### ISSUE THREAD

**Issue by MGL74** [MscrmTools/XrmToolBox#1366]
[Write your comment/feedback/issue here]
I cannot connect o my environments anymore, thus the whole tool suite became useless with the last update.

I get the following error when trying to use connection, created in previous version of your tool.

error: Authentication Failure
Stack Trace	: at Microsoft.Identity.Core.WsTrust.WsTrustWebRequestManager.<GetWsTrustResponseAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.WsTrust.CommonNonInteractiveHandler.<GetWsTrustResponseAsync>d__7.MoveNext()
Please help me on that.

---
- Connection Controls Version: 1.2024.9.59
- XrmToolBox Version: 1.2023.12.68

**Comment by MscrmTools** [comment]
Please update again. Something was wrong on the first attempt like for many people

**Comment by omnisip** [comment]
I just downloaded from the site.  [XrmToolBox v1.2024.9.69](https://www.xrmtoolbox.com/releases/xrmtoolbox-v1.2024.9.69)

I can't login with any connection or with any credential.  I have tried certificates, clientId, etc.  I usually use Microsoft Login Control, but it always fails like below.  

![image](https://github.com/user-attachments/assets/7d561b17-dd61-4186-9080-4c03b289b153)

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:53:25
Error	: A password is required.
Parameter name: CrmPassword
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:53:28
Error	: A password is required.
Parameter name: CrmPassword
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:53:37
Error	: You don't have permission to access any of the environments in the Microsoft Power Platform region that you specified. If you're not sure which region your environment resides in, choose "Don't know" for the Power Platform region and try again. Otherwise check with your Power Platform administrator.
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:54:08
Error	: A password is required.
Parameter name: CrmPassword
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:54:12
Error	: A user name is required.
Parameter name: CrmUserName
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:54:19
Error	: A password is required.
Parameter name: CrmPassword
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:54:20
Error	: A password is required.
Parameter name: CrmPassword
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 10/18/2024
Time	: 15:57:18
Error	: A Dataverse server name is required.
Parameter name: CrmServerName
Stack Trace	: Not Provided
======================================================================================================================

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 15:57:34
Error	: AADSTS50126: Error validating credentials due to invalid username or password. Trace ID: ee4f0d23-e580-4229-b3cf-de3e00f23000 Correlation ID: 5b5e9628-aa5e-4b52-a5ab-29a7ea381210 Timestamp: 2024-10-18 21:57:34Z
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================
Inner Exception Level 1	: 
Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 15:57:34
Error	: Response status code does not indicate success: 400 (BadRequest).
Stack Trace	: at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()
======================================================================================================================

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 15:57:51
Error	: AADSTS50126: Error validating credentials due to invalid username or password. Trace ID: 4a3235bb-aad5-43de-9757-45195c574800 Correlation ID: f9f47a60-a02b-4410-8aa5-b28815ff397b Timestamp: 2024-10-18 21:57:51Z
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================
Inner Exception Level 1	: 
Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 15:57:51
Error	: Response status code does not indicate success: 400 (BadRequest).
Stack Trace	: at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()
======================================================================================================================

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 15:58:04
Error	: AADSTS50126: Error validating credentials due to invalid username or password. Trace ID: a2d00396-d312-45f6-a615-33e4e17c4300 Correlation ID: bd1f65c4-2976-43e7-b6b8-50adc359ab29 Timestamp: 2024-10-18 21:58:04Z
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================
Inner Exception Level 1	: 
Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 15:58:04
Error	: Response status code does not indicate success: 400 (BadRequest).
Stack Trace	: at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()
======================================================================================================================

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/18/2024
Time	: 16:03:13
Error	: Integrated Windows Auth is not supported for managed users. See https://aka.ms/adal-iwa for details.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

**Comment by omnisip** [comment]
Hmm.... it started working when I tried to connect, but not when I double clicked it in the connections.

**Comment by MscrmTools** [comment]
@omnisip So is there still an issue? not sure to get it
