### ISSUE TITLE
Can't connect to Microsoft Dataverse - O365 - connection Type.  Version 1.2024.9.69

### ISSUE THREAD

**Issue by rcevallosq** [MscrmTools/XrmToolBox#1368]
Hi. Please your kind help.
I have downloaded the version: 1.2024.9.69**, in a new folder location.**
I have **deleted all the programs in the folder:** C:\Users\rcevallos\AppData\Roaming\MscrmTools\XrmToolBox
I am trying to create my connection using the "Microsoft Login"
I am getting the error:  Unable to connect.
I have tried with other connection types and is the same result, please your help.

![image](https://github.com/user-attachments/assets/e18e2f08-a482-4154-ae6a-2bb727e95458)

Source	: Not Provided
Method	: Not Provided
Date	: 10/24/2024
Time	: 4:32:10 PM
Error	: A Dataverse server name is required.
Parameter name: CrmServerName
Stack Trace	: Not Provided

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Date	: 10/24/2024
Time	: 4:36:16 PM
Error	: Service returned error. Check InnerException for more details
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, UserIdentifier& userOut, CrmLogEntry logSink, Boolean useGlobalDisco, Boolean useDefaultCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)

**Comment by janis-veinbergs** [comment]
Broken for me too. If using Connection String option I get this stuff:

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	29.10.2024 10:20:26  Unable to connect to CRM: Method not found: 'System.String Microsoft.Xrm.Sdk.Organization.OrganizationDetail.get_SchemaType()'.
Source	: Microsoft.Xrm.Tooling.Connector
Method	: RefreshInstanceDetails
Date	: 29.10.2024
Time	: 10:20:26
Error	: Method not found: 'System.String Microsoft.Xrm.Sdk.Organization.OrganizationDetail.get_SchemaType()'.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.RefreshInstanceDetails(IOrganizationService crmService, Uri uriOfInstance)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DoDirectLogin(Boolean IsOnPrem)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
```

**Comment by janis-veinbergs** [comment]
Ah, I manually downloaded .zip from releases and copied files over within my existing xrmtoolbox folder and now it works.
