### ISSUE TITLE
[BUG]Xrm toolbox for MS dataverse and MS dynamics 365 unhandled exception

### ISSUE THREAD

**Issue by Sarahhiggins1** [MscrmTools/XrmToolBox#1374]
**Describe the bug**
I updated to the latest version of the xrm toolkit (i had to do an uninstall and start over), I'm able to download some of the tools from the library but when I try to download the Bulk Data Updater, I get thr following error.

Xrm ToolBox for Microsoft Dataverse and Microsoft Dynamics 365 (v1.202...

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

An error occured while copying files: The process cannot access the file C:\Users\higgis\AppData\Roaming\Mscrm Tools\Xrm ToolBox\Plugins\R appen.XTB.BDU\System.Collections.Immutable.dll' because it is being used by another process.

Trying to install the Bulk Data Updater from.the Tools Library.

**Expected behavior**
Successful install

**Screenshots**
If applicable, add [screenshots](url) to help explain your problem.

**Desktop (please complete the following information):**
 - XrmToolbox Version - 1.2024.9.69
 - Tool version

**Additional context**

**Comment by erikhagby-ae** [comment]
Same problem here. No issue before update to latest version.
I'm trying to use the Easy Translator plugin

**Comment by MscrmTools** [comment]
@rappen Can you check if it's possible to install a new tool of yours when another one has been already used?

**Comment by MscrmTools** [comment]
@erikhagby-ae Can you provide steps repro + screenshot?

**Comment by swokim** [comment]
Hi all, I still face the following error message even after deleting ALL connections and creating ONE new connection. Any idea how to solve this?

<img width="1905" height="1071" alt="Image" src="https://github.com/user-attachments/assets/481b6d9d-2281-4dcd-b260-3f4d47e49ba7" />

************** Exception Text **************
System.Exception: An error occured while copying files: The process cannot access the file 'C:\Users\ext.eljakim.seemann\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Rappen.XTB.BDU\System.Collections.Immutable.dll' because it is being used by another process.
   at XrmToolBox.ToolLibrary.ToolLibrary.PerformInstallation(PluginUpdates updates, Form form)
   at XrmToolBox.ToolLibrary.Forms.ToolLibraryForm.<>c__DisplayClass121_0.<tsbBulkInstall_Click>b__5(Object s, DoWorkEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by MscrmTools** [comment]
The usage of tool library has nothing to do with connections. No need to delete them.

@rappen, calling you again. Did you get other report of this issue on your side?

**Comment by rappen** [comment]
I haven't got this type of report.
BDU is using the Immutable file and included when the BDU tool is installed.
@swokim - can you test to close all instance of XrmToolBox, then try to manually delete the file:
`C:\Users\ext.eljakim.seemann\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Rappen.XTB.BDU\System.Collections.Immutable.dll`, then start XrmToolBox and try to install BDU again?

**Comment by rappen** [comment]
Hi - I would delete the whole folder, and the DLL file Rappen.XTB.BDU.dll and try to install BDU again.
I have no explanation for the error that occurs... :-/
