### ISSUE TITLE
[BUG] Toolbox creates fresh connection for each request

### ISSUE THREAD

**Issue by skfd** [MscrmTools/XrmToolBox#1375]
**Describe the bug**
Toolbox started popping up login dialog while doing some operations, and after some time this causes a 2FA to pop up. I think CRM is rate limiting the session.

**To Reproduce**
It's definitely something with my installation, I can reproduce it by just refreshing Plugin Registration Tool 10 times.

**Expected behavior**
It should not popup 2FA dialogue however long I use Toolbox.

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2024.9.69
 - Tool version: not a tool issue

**Additional context**
It's something to do with my job provided computer that limits which paths I am able to write to. I found this in logs. Is this something I can fix?

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	12/19/2024 4:44:48 PM  Error occurred in CrmServiceClientTokenCache.AfterAccessNotification(). 
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\__\AppData\Local\Temp\{25287241-e0ca-4bd0-8b68-030987967f2b}' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache.AfterAccessNotification(TokenCacheNotificationArgs args)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	12/19/2024 4:44:48 PM  Error occurred in CrmServiceClientTokenCache.AfterAccessNotification(). 
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\__\AppData\Local\Temp\{25287241-e0ca-4bd0-8b68-030987967f2b}' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache.AfterAccessNotification(TokenCacheNotificationArgs args)
Source	: Not Provided
Method	: Not Provided
Date	: 12/19/2024
Time	: 4:44:48 PM
Error	: Error occurred in CrmServiceClientTokenCache.AfterAccessNotification(). 
Exception Details : System.UnauthorizedAccessException: Access to the path 'C:\Users\__\AppData\Local\Temp\{25287241-e0ca-4bd0-8b68-030987967f2b}' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache.AfterAccessNotification(TokenCacheNotificationArgs args)
Stack Trace	: Not Provided
```

**Comment by MscrmTools** [comment]
Unfortunately not...

I'm using the user Temp folder, so it's not configurable so far.

This is something I could change for a next release

**Comment by skfd** [comment]
I will look into it further, it's probably some restrictions on my corporate machine. Very much an edge case...

**Comment by chironh** [comment]
@Ruderg https://github.com/MscrmTools/XrmToolBox/issues/1363#issuecomment-4342843128

**Comment by skfd** [comment]
I did not fix it, or found exact reason for it. Can not reproduce on new machine
