### ISSUE TITLE
Can't Load SiteMap

### ISSUE THREAD

**Issue by glenwol** [MscrmTools/XrmToolBox#171]
I have downloaded the latest version from GitHub to run on the original release of CRM 2015.  

When I use the SiteMap editor, I get the following error when trying to load the site map from my server.

PLEASE HELP!!!!
Thanks.
---------------------------------------------------------------------------------------------------------------------------------

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at MsCrmTools.SiteMapEditor.AppCode.TreeNodeHelper.AddTreeViewNode(Object parentObject, XmlNode xmlNode, SiteMapEditor form, Boolean isDisabled)
   at MsCrmTools.SiteMapEditor.AppCode.TreeNodeHelper.AddTreeViewNode(Object parentObject, XmlNode xmlNode, SiteMapEditor form, Boolean isDisabled)
   at MsCrmTools.SiteMapEditor.AppCode.TreeNodeHelper.AddTreeViewNode(Object parentObject, XmlNode xmlNode, SiteMapEditor form, Boolean isDisabled)
   at MsCrmTools.SiteMapEditor.SiteMapEditor.DisplaySiteMap()
   at MsCrmTools.SiteMapEditor.SiteMapEditor.<LoadSiteMap>b__e(RunWorkerCompletedEventArgs e)

**Comment by MscrmTools** [comment]
Hi,

This could occur if SiteMapXml starts with a comment but I'm not even sure.

I am able to load SiteMap from CRM 2015 OnPrem and CRM 2015 Update 1 Online without any problem

**Comment by glenwol** [comment]
How can I repair it?

**Comment by MscrmTools** [comment]
if you are using CRM 2015 OnPrem, I would get the sitemap from table SiteMap in your organization database to see what it looks like

**Comment by MscrmTools** [comment]
Ok, someone else provided help to identify this bug.

It is due to comment with text only inside

**Comment by MscrmTools** [comment]
Fixed
