### ISSUE TITLE
SiteMap Editor crashes XrmToolBox when group is moved up multiple times

### ISSUE THREAD

**Issue by mdocter** [MscrmTools/XrmToolBox#293]
**SiteMap Editor - symptom:**
When I create a new group below an Area, the group is placed as last group. When I rapidly move it up multiple times by using the green arrow-up icon button, the whole XrmToolBox crashes.

**Note:**
This only happens after working with the tool for a while (multiple modifications like cut/paste groups and publications etc.). I tried to reproduce it by opening a fresh XrmToolBox instance, opening the SiteMap Editor, Load SiteMap, Create a group and reorder it, but in that case it didn't happen... so the exact order of events to make it crash is currently a mystery to me. Today I was cleaning up a pretty large SiteMap and it already happened twice. And I had it before. Maybe other users noticed the same behavior and can help to pinpoint the order of events.

The following three errors are logged in the Windows Event Log:

```xml
Log Name:      Application
Source:        Application Error
Date:          17-12-15 14:38:14
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      lt-md
Description:
Faulting application name: XrmToolBox.exe, version: 1.2015.11.5, time stamp: 0x563a8e6b
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f38c3
Exception code: 0xc000041d
Fault offset: 0x000000000002a1c8
Faulting process id: 0x413c
Faulting application start time: 0x01d138b41ac9c054
Faulting application path: H:\Tools\XrmToolBox2\XrmToolBox.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: c3f552ba-0ddf-42a5-9dee-f333dd893390
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-17T13:38:14.000000000Z" />
    <EventRecordID>15118</EventRecordID>
    <Channel>Application</Channel>
    <Computer>lt-md</Computer>
    <Security />
  </System>
  <EventData>
    <Data>XrmToolBox.exe</Data>
    <Data>1.2015.11.5</Data>
    <Data>563a8e6b</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10240.16384</Data>
    <Data>559f38c3</Data>
    <Data>c000041d</Data>
    <Data>000000000002a1c8</Data>
    <Data>413c</Data>
    <Data>01d138b41ac9c054</Data>
    <Data>H:\Tools\XrmToolBox2\XrmToolBox.exe</Data>
    <Data>C:\WINDOWS\system32\KERNELBASE.dll</Data>
    <Data>c3f552ba-0ddf-42a5-9dee-f333dd893390</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          17-12-15 14:38:11
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      lt-md
Description:
Faulting application name: XrmToolBox.exe, version: 1.2015.11.5, time stamp: 0x563a8e6b
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f38c3
Exception code: 0xe0434352
Fault offset: 0x000000000002a1c8
Faulting process id: 0x413c
Faulting application start time: 0x01d138b41ac9c054
Faulting application path: H:\Tools\XrmToolBox2\XrmToolBox.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 4c137b68-a3c4-4c40-ba98-366f9028345b
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-17T13:38:11.000000000Z" />
    <EventRecordID>15116</EventRecordID>
    <Channel>Application</Channel>
    <Computer>lt-md</Computer>
    <Security />
  </System>
  <EventData>
    <Data>XrmToolBox.exe</Data>
    <Data>1.2015.11.5</Data>
    <Data>563a8e6b</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10240.16384</Data>
    <Data>559f38c3</Data>
    <Data>e0434352</Data>
    <Data>000000000002a1c8</Data>
    <Data>413c</Data>
    <Data>01d138b41ac9c054</Data>
    <Data>H:\Tools\XrmToolBox2\XrmToolBox.exe</Data>
    <Data>C:\WINDOWS\system32\KERNELBASE.dll</Data>
    <Data>4c137b68-a3c4-4c40-ba98-366f9028345b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          17-12-15 14:38:11
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      lt-md
Description:
Application: XrmToolBox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-17T13:38:11.000000000Z" />
    <EventRecordID>15115</EventRecordID>
    <Channel>Application</Channel>
    <Computer>lt-md</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: XrmToolBox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

</Data>
  </EventData>
</Event>
```

**Comment by rappen** [comment]
I've had the problem too on a couple of occasions lately.
Unfortunately I have no idea how to reproduce it...
But can confirm the problem exists :)

**Comment by rappen** [comment]
Actually I just got it again... :-1: 
```
An unexpected error occured: System.ComponentModel.Win32Exception (0x80004005): Det gick inte att skapa fönsterreferensen.
   vid System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   vid System.Windows.Forms.Control.CreateHandle()
   vid System.Windows.Forms.Control.get_Handle()
   vid System.Windows.Forms.Control.CreateGraphicsInternal()
   vid System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   vid System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   vid System.Windows.Forms.Control.WndProcException(Exception e)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   vid System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   vid System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   vid System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   vid System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   vid XrmToolBox.Program.Main(String[] args)

One reason can be that at least one file is locked by Windows. Please unlock each locked files or unlock XrmToolBox.zip before extracting its content
```

**Comment by MscrmTools** [comment]
Difficulty is error message does not identify source location for the error

**Comment by MscrmTools** [comment]
tried to fix it by removing handlers while processing the move. Please re open if next release does not really fix it

**Comment by pmalecka** [comment]
The issue still exists. Sitemap Editor randomly crashes. The error description is similar to this one. http://stackoverflow.com/questions/222649/winforms-issue-error-creating-window-handle

**Comment by pmalecka** [comment]
<img width="323" alt="xrmtoolbox_crash" src="https://cloud.githubusercontent.com/assets/13047492/11935148/8f743450-a806-11e5-8c69-d6199065177e.png">

as you can see, once the number of user objects reaches 10 000, it is killed. So that's why you cannot easily reproduce the issue. It takes a fair bit of time and using the SitemapEditor to reach that number of objects.

**Comment by MscrmTools** [comment]
Ok, I read some content about user and gdi objects and it seems I have to handle user controls removal much better. I will try to work on this

**Comment by MscrmTools** [comment]
Yoohoo!
I found how to fix this issue! user objects and GDI objects remain Under 400 when navigating in SiteMap treeview!

**Comment by pmalecka** [comment]
Awesome! Can I try it out - is it in the latest commit?

**Comment by MscrmTools** [comment]
Just need to commit the code, it should be done soon

**Comment by pmalecka** [comment]
Can't wait to test it out :). How did you fix it?

**Comment by MscrmTools** [comment]
Disposed user control displayed when changing node selection (fixed User Object leaks)
Disposed Tooltip explicitely when disposing user controls (fixed GDI object leaks)

**Comment by MscrmTools** [comment]
Pre release is available

**Comment by pmalecka** [comment]
it's rock solid, user and gdi objects stay below 200 for me. Thanks for the fix Tanguy

**Comment by mdocter** [comment]
That's great news guys! Thanks Tanguy for fixing this annoying bug! I'll give it a try soon.
