### ISSUE TITLE
Cannot connect via authenticated proxy

### ISSUE THREAD

**Issue by davidlb** [MscrmTools/XrmToolBox#330]
I cannot connect to online instances via proxy. It requires authentication. I tried to manually changed config file by using:

```XML 
 <system.net>
    <defaultProxy useDefaultCredentials="true" >
    </defaultProxy>
</system.net>
```

To be sure, I ran LoginControlTester.exe from CRM SDK and it works.

Error log: 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System
Method	: GetRequestStream
Date	: 01/02/2016
Time	: 12:06:04
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.Xrm.Tooling.Connector.DeviceIdManager.ExecuteRegistrationRequest(String url, DeviceRegistrationRequest registrationRequest)
   at Microsoft.Xrm.Tooling.Connector.DeviceIdManager.RegisterDevice(Guid applicationId, Uri issuerUri, LiveDevice device)
   at Microsoft.Xrm.Tooling.Connector.DeviceIdManager.RegisterDevice(Guid applicationId, Uri issuerUri, String deviceName, String devicePassword)
   at Microsoft.Xrm.Tooling.Connector.DeviceIdManager.LoadOrRegisterDevice()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GenerateDeviceCreds()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

**Comment by MscrmTools** [comment]
This is not enough, please try with this code:
```XML
<system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy autoDetect="True" bypassonlocal="False" />
    </defaultProxy>
  </system.net>
```

**Comment by davidlb** [comment]
Ok, I've updated the config file and here is the full error log:

`Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Asia Pacific Area) URI is = https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Asia Pacific Area) URI is = https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System.ServiceModel
Method	: Retrieve
Date	: 01/02/2016
Time	: 13:38:05
Error	: Metadata contains a reference that cannot be resolved: 'https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=0'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 01/02/2016
Time	: 13:38:05
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System.ServiceModel
Method	: Retrieve
Date	: 01/02/2016
Time	: 13:38:05
Error	: Metadata contains a reference that cannot be resolved: 'https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=0'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 01/02/2016
Time	: 13:38:05
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
`

**Comment by davidlb** [comment]
And this is the succssful log file from LoginControlTester.exe where my org name have replaced by __myorg__

> 
Microsoft.Xrm.Tooling.CrmConnectControl Warning: 4 : MessageSecurityException while trying to connect Discovery Server, (India) URI is = https://disco.crm8.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.CrmConnectControl Information: 8 : Found 1 Org(s)
Microsoft.Xrm.Tooling.CrmConnectControl Verbose: 16 : DiscoveryServer indicated organization service location = https://__myorg__.api.crm5.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.CrmConnectControl Information: 8 : Organization Service URI is = https://__myorg__.api.crm5.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.CrmConnectControl Information: 8 : Validating connection to Microsoft Dynamics CRM...
Microsoft.Xrm.Tooling.CrmConnectControl Information: 8 : Login Status in Connect is =  Validating connection to Microsoft Dynamics CRM...
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : User Specified Org details are used.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Found 1 Org(s)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoveryServer indicated organization service location = https://__myorg__.api.crm5.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Organization Service URI is = https://__myorg__.api.crm5.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : ConnectAndInitCrmOrgService - Requesting connection to Org with CRM Version: 7.1.1.4314
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : ConnectAndInitCrmOrgService - Proxy created, total elapsed time: 00:00:00.3070307
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : User Org (org01fbe2dc) found in Discovery Server  - ONLY ORG FOUND
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Beginning Validation of CRM Connection
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Validation of CRM Connection Complete, total duration: 00:00:03.0793079
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : New Batch Manager Created, Max #of Batches:50000, Max #of RequestsPerBatch:5000
Microsoft.Xrm.Tooling.CrmConnectControl Information: 8 : Login Status in Connect is =  Connection to CRM Complete

**Comment by davidlb** [comment]
I don't get why this issue have been closed, the problem is still here.
With fresh copy of xrmtoolbox, I can connect with direct internet connection (at home) but not via the office authenticated proxy (I just changed the settings to use the Internet Explorer configured proxy).
In IE, proxy configuration is done via proxy auto-config script.

If you need me to do some tests or more details, please tell me.

**Comment by MscrmTools** [comment]
Your previous post was talking about a successful connection log, this is why I closed the issue. 
If you are using a auto config script, then you need to adapt the proxy configuration following the MSDN documentation : https://msdn.microsoft.com/en-us/library/sa91de1e(v=vs.110).aspx

**Comment by davidlb** [comment]
Sorry, it was not clear. With the same config file, I can connect using the SDK tool LoginControlTester.exe to my Online instance but not with xrmtoolbox so I'm pretty sure it's not related to the config file and it's probably a bug in xrmtoolbox

In my previous messages, there is one log file on the successful connection with Logincontroltester and the error log from xrmtoolbox.

**Comment by MscrmTools** [comment]
Maybe the LoginControlTester uses proxy information from IE, don't know...
But the log from XrmToolBox does indicates the problem is with the proxy so you should configure the config file to use that script used in IE

**Comment by davidlb** [comment]
I tried mostly all combinations of settings in Xrmtoolbox and config file but I didn't succeed to pass the proxy. 

```XML
    <defaultProxy useDefaultCredentials="true">
      <proxy scriptLocation="http://proxypac.net.xxxx.com/config-gtb.pac" />
    </defaultProxy>```

**Comment by davidlb** [comment]
I manage to get the proxy server ip. I did a fresh install, I set the server as custom proxy in XrmToolbox and I tried with and without custom authentication, I still have the Error 407 Proxy Authentication Required.
