### ISSUE TITLE
Unable to Open New Plugins After Laptop Hibernates

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#373]
Previous to the new Microsoft Connections from January I never had to restart the XTB, even when hibernating, switching networks, etc.  Now I'm getting this error message when I click on a plugin to open it:

![image](https://cloud.githubusercontent.com/assets/9728423/13878065/3361ce06-ece5-11e5-9a3d-783b4c55a6a1.png)

Attempting to reconnect to CRM gives this error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ServiceModel.FaultException: ID3082: The request scope is not valid or is unsupported.
   at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateCrossRealm(ClientCredentials clientCredentials, String appliesTo, Uri crossRealmSts)
   at Microsoft.Xrm.Sdk.Client.ServiceProxy`1.AuthenticateCore()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CheckForConnectionTokenTimeOut()
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.get_OrganizationServiceProxy()
   at McTools.Xrm.Connection.ConnectionManager.WorkerRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/XrmToolBox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/XrmToolBox.Extensibility.DLL
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.10586.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0.1072
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly Version: 1.2016.1.93
    Win32 Version: 1.2016.1.93
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2016.1.93
    Win32 Version: 1.2016.1.93
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2016.1.93
    Win32 Version: 1.2016.1.93
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
DLaB.AttributeManager
    Assembly Version: 1.2016.2.6
    Win32 Version: 1.2016.2.6
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DLAB.ATTRIBUTEMANAGER.DLL
----------------------------------------
DLaB.Common
    Assembly Version: 1.0.5861.28404
    Win32 Version: 1.0.5861.28404
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DLAB.COMMON.DLL
----------------------------------------
DLaB.EarlyBoundGenerator
    Assembly Version: 1.2016.2.6
    Win32 Version: 1.2016.2.6
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DLAB.EARLYBOUNDGENERATOR.DLL
----------------------------------------
DLaB.Xrm
    Assembly Version: 1.0.5862.23371
    Win32 Version: 1.0.5862.23371
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRM.DLL
----------------------------------------
DLaB.Xrm.Entities
    Assembly Version: 1.0.5870.30963
    Win32 Version: 1.0.5870.30963
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRM.ENTITIES.DLL
----------------------------------------
DLaB.XrmToolboxCommon
    Assembly Version: 1.2016.2.6
    Win32 Version: 1.2016.2.6
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRMTOOLBOXCOMMON.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2016.1.7
    Win32 Version: 1.2016.1.7
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2015.12.20
    Win32 Version: 1.2015.12.20
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2016.1.30
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0000.1088
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
MetadataViewProxies_c25f0e23-f2ff-42fd-8621-ba06a0ce6319
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.303
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.18.0.0
    Win32 Version: 2.18.00000.0000
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    Assembly Version: 4.0.0.0
    Win32 Version: 14.0.23107.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IdentityModel.Selectors
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
Microsoft.Xrm.Sdk.Deployment
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0000.1088
    CodeBase: file:///C:/CRM%20Tools/XrmToolBox/Microsoft.Xrm.Sdk.Deployment.DLL
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ICSharpCode.AvalonEdit
    Assembly Version: 5.0.1.0
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
Yahoo.Yui.Compressor
    Assembly Version: 1.7.0.0
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.dll
----------------------------------------
EcmaScript.NET.modified
    Assembly Version: 0.1.1.0
    Win32 Version: 1.2016.1.30
    CodeBase: file:///C:/CRM%20TOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Restarting the XTB resolves any issues, but, is kind of annoying, since I loose any work I currently have open...

**Comment by daryllabar** [comment]
Just noticed I'm on 1.2016.1.30.  Will try the latest and greatest dev version to see if it somehow has been resolved....

**Comment by MscrmTools** [comment]
I'm not sure I will be able to do something about it...

**Comment by daryllabar** [comment]
This appears to have been resolved with the latest version.
