### ISSUE TITLE
Can not connect with CRM 2015 on premise 

### ISSUE THREAD

**Issue by SLewis-Venteon** [MscrmTools/XrmToolBox#387]
Using version XRMToolBox v1.2016.3.30 - I am not able to make a connection with CRM 2015 on premise. Connected fine with my Dev environment that is not ADFS. I have tried connection string also but still get the message "Unable to connect to Dynamics CRM" Does anyone have a solution or similar problem?

**Comment by MscrmTools** [comment]
As mentionned in the issue you commented, can you explain if the environment you are trying to connect to uses ADFS.
Also, latest version allows you to use connection string. Please use it if connection wizard cannot connect.
Finally, there should be a log file in the XrmToolBox root folder that explains the connection error

**Comment by SLewis-Venteon** [comment]
Yes the environment is ADFS.  I have also tried connection string.  See attempts below, first is with connection wizard, second is with connection string.

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System.ServiceModel
Method	: ReadResponse
Date	: 4/5/2016
Time	: 11:23:30 AM
Error	: ID3242: The security token could not be authenticated or authorized.
Stack Trace	: at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System.ServiceModel
Method	: ReadResponse
Date	: 4/5/2016
Time	: 11:24:00 AM
Error	: ID3242: The security token could not be authenticated or authorized.
Stack Trace	: at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM

**Comment by MscrmTools** [comment]
Can you share your connectionstring with hidden url, account and password?

**Comment by SLewis-Venteon** [comment]
Url=https://******URL**********/***OrgName**; Domain=**********; Username=**********; password=************

**Comment by MscrmTools** [comment]
Ok, with the latest SDK assemblies, you need to specify the AuthType property, which should be AuthType=IFD
Please use the link in the connection wizard to see the MSDN page that explains connection string parameters

**Comment by SLewis-Venteon** [comment]
Added "AuthType=IFD" in front of URL, still same error

**Comment by MscrmTools** [comment]
Also, some IFD requires that domain and user name are concated together like Url=https://***URL****/OrgName; Username=domain\username; password=*********

**Comment by SLewis-Venteon** [comment]
That was the issue, I am connected using the wizard.  Just needed to add the domain again to the username.   Thanks for your help!
