### ISSUE TITLE
Unable to connect to a CRM 2015/2016 Online Environment

### ISSUE THREAD

**Issue by jweresch** [MscrmTools/XrmToolBox#416]
Was wondering what types of issues could be preventing me from connecting?  The error message mentions using the unique org name, but that doesn't seem to work.  One environment is 2016 and the other 4 are still 2015.  
This worked fine last year.  When I was unable to connect this year, I upgraded to the latest version and still no luck.
Office 365 authentication.

**Comment by MscrmTools** [comment]
To get more information on why the connection did not succeed on your organization, please activate the trace by following [this procedure](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox)

Then, please post the log here so we can analyze what the problem is

**Comment by jweresch** [comment]
Thanks.  I followed the steps and came up with the following (see below).  I can log into this instance fine, so not sure why its access denied?

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source          : System.ServiceModel
Method : ReadResponse
Date      : 5/16/2016
Time      : 11:25:58 AM
Error      : MSIS7068: Access denied.
Stack Trace         : at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateWithADFSForOrgId(AuthenticationCredentials authenticationCredentials, Uri identifier)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()

**Comment by MscrmTools** [comment]
Is your office 365 federated with your local ad?

**Comment by jweresch** [comment]
Yes it is

**Comment by MscrmTools** [comment]
Ok so there must be some specific connectionstring for that but I don't know what is it since I don't have this kind of deployment available

**Comment by jweresch** [comment]
ok, does this also explain why people inside they network can connect and me outside cannot?

**Comment by MscrmTools** [comment]
Couldn't say...

**Comment by jweresch** [comment]
ok, so due to office 365 being federated there is no work around at this time to get connected?

**Comment by MscrmTools** [comment]
I don't know the real answer but if you use connection strings, then my tool does not perform any custom behavior but let Microsoft assemblies do the connection.
If it does not work with connection strings, I'm not responsible.
I'm quite sure you should be able to connect but I don't know the expected connection string format for office 365 federated with local ad

**Comment by ChrisGrohHS** [comment]
It looks like there is an issue with the Microsoft assemblies. We were able to get a connection string that was failing to work by updating to the 8.1.0 and adding binding redirects for the two Microsoft.Xrm.Tooling DLLs.

**Comment by MscrmTools** [comment]
Great news! I will update sdk assemblies for next release

**Comment by MscrmTools** [comment]
As mentioned above, it's a problem with CRM SDK assemblies. 
Next release is ready for delivering with SDK assemblies updated
