### ISSUE TITLE
Cannot Connect to Office365 with Dual Factor via connection string

### ISSUE THREAD

**Issue by sarias23** [MscrmTools/XrmToolBox#452]
AuthType=Office365;url=https://uniqueorgname.crm.dynamics.com/ uniqueorgname;loginprompt=always 

I have tried many different connection strings to no avail. I have spoken with Microsoft and they cant assist because this is a 3rd party app. I have read several different threads within this site in regards to similar issues and it seems nothing is working. Just to note I have the newest version of XRM toolbox. As well if I turn off dual factor I can utilize the wizard and connect just find. Any assistance on what I am doing wrong would be great.

I have also put in my username in the connectionstring since it stats in the connection log that username is required. Am I using the incorrect authtype?

**Comment by sarias23** [comment]
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 7/11/2016
Time	: 3:46:41 PM
Error	: Authentication Failure
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Sdk
Method	: Assert
Date	: 7/11/2016
Time	: 3:47:59 PM
Error	: clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!
Stack Trace	: at Microsoft.Xrm.Sdk.ClientExceptionHelper.Assert(Boolean condition, String message)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.GetIdentityProvider(ClientCredentials clientCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()

**Comment by sarias23** [comment]
With username in connection string I get this:

Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 7/11/2016
Time	: 3:59:18 PM
Error	: Authentication Failure
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
Method	: HandleReturnMessage
Date	: 7/11/2016
Time	: 3:59:27 PM
Error	: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateTokenWithOrgIdForCrm(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 7/11/2016
Time	: 3:59:27 PM
Error	: Authentication Failure
Stack Trace	: Not Provided

**Comment by MscrmTools** [comment]
If you read the wiki, I explain how to connect with MFA.
At least, it worked for me

**Comment by sarias23** [comment]
can you direct me where in the wiki specifically to look? thank you for your time.

**Comment by sarias23** [comment]
Thanks for the Fix I was able to get everything taken care of great guides!!

**Comment by sarias23** [comment]
OK I can connect but as soon as I click on any plugin already in the XRM toolbox I get this error. Sorry just not sure what I need to do from here.. It doesnt make sense. Error below.
![crmerror](https://cloud.githubusercontent.com/assets/20327867/16787722/57cbee9c-4853-11e6-9f41-5a90db199f4b.PNG)

**Comment by MscrmTools** [comment]
Ok, this one is maybe on me...

I would need to perform some test again because when using MFA, the endpoint used is different so maybe I do not return the appropriate one.

Unfortunately, I'm on holidays without proper development workstation so I can't help you for the next two weeks

**Comment by sarias23** [comment]
Just coming back to see if anything was found on this issue as of yet. I know you probably just came back from holiday. but i was wanting to see if you needed any further info.

**Comment by sarias23** [comment]
Just curious if there was any possible updates?

**Comment by sarias23** [comment]
Hello good sir. Any updates for dual factor authentication in a future update?

**Comment by MscrmTools** [comment]
I checked the code and the appropriate endpoint is returned... 

I know it is not something easily doable but if you could provide (privately) your connection details, I could troubleshoot better

**Comment by MscrmTools** [comment]
This issue will be resolved in September release
