### ISSUE TITLE
Plugin Registration Plugin issue

### ISSUE THREAD

**Issue by zsoltzombik** [MscrmTools/XrmToolBox#484]
I was trying to open the Plugin Registration Plugin. And have got the following error message:
"Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.LoadNodes(ICrmTreeNode[] rootNodes)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)"

**Comment by shytikov** [comment]
Hi, do you have most recent version of `PluginRegistation`?

**Comment by shytikov** [comment]
I have created issue in the repository: https://github.com/Innofactor/PluginRegistration/issues/10

Another question would be, just guessing, could it be that you have two instances of the `PluginRegistration` opened?

Can you tell more about environment and steps that lead to such en exception?

**Comment by michaelmmcrae1** [comment]
@shytikov @zsoltzombik 
I'm having this issue now when connecting to a cloud instance.
How did you resolve this? I see no mention of resolution in relation to this ticket.

Thanks in advance!
