### ISSUE TITLE
Error	: Connection to CRM is not established. Aborting process + Output file was not updated or not found!

### ISSUE THREAD

**Issue by naveenjoe** [MscrmTools/XrmToolBox#522]
The xrmtoolbox version in use is 1.2016.10.2
I am trying to connect to CRM 2016 org (8.1.0.359) (DB 8.1.0.359)
I am able to make a connection to this org however unable to generate the early bound classes due to the below error:

CRM Authentication Type Detected: Federation
Executing "C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://*****.fi/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /username:"crmdev" /password:"************" /domain:"*****" 
Executing "C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://*****.fi/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\Entities.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"crmdev" /password:"************" /domain:"*****" 
Executing "C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://*****.fi/XRMServices/2011/Organization.svc" /generateActions /out:"C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\Actions.cs" /namespace:"CrmEarlyBound" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /username:"crmdev" /password:"************" /domain:"progman" 
CrmSvcUtil : CRM Service Utility [Version 8.1.0.7711]
c 2015 Microsoft Corporation. All rights reserved

CrmSvcUtil : CRM Service Utility [Version 8.1.0.7711]
c 2015 Microsoft Corporation. All rights reserved

CrmSvcUtil : CRM Service Utility [Version 8.1.0.7711]
c 2015 Microsoft Corporation. All rights reserved

Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date	: 13:53:56
Time	: 15-11-2016
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: mscorlib
Method	: InvokeMethod
Date	: 13:53:56
Time	: 15-11-2016
Error	: Exception has been thrown by the target of an invocation.
Stack Trace	: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

Inner Exception Level 1	: 
Source	: CrmSvcUtil
Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date	: 13:53:56
Time	: 15-11-2016
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)

CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date	: 13:53:56
Time	: 15-11-2016
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

Output file was not updated or not found!  C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\Entities.cs
Output file was not updated or not found!  C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\Actions.cs
Output file was not updated or not found!  C:\Users\Naveen Manoharan\Downloads\Compressed\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs

**Comment by MscrmTools** [comment]
Hi, this is a problem with Early Bound Generator, not XrmToolBox itself, please create an issue in the [following repository](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues)

**Comment by naveenjoe** [comment]
Okay. Thanks for the guidance. Appreciate it!
