### ISSUE TITLE
NullReferenceException during start

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#536]
I am getting this exception everytime I start XrmToolBox. Is anyone else getting this?

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at XrmToolBox.MainForm.GetVisibleScrollbars(ScrollableControl ctl)
   at XrmToolBox.MainForm.AdaptPluginControlSize()
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MscrmTools** [comment]
I don't reproduce this exception... what version of XTB?

**Comment by rajyraman** [comment]
Seems to be happening only on my home machine. I should probably clear out the folder and see whether it goes away. Using the most recent version.

**Comment by rajyraman** [comment]
pnlPlugins seems to be null in AdaptPluginControlSize. Was able to reproduce consistently with the latest  codebase. Added a null check and no more exception.
