### ISSUE TITLE
Cannot connect to CRM test environment?

### ISSUE THREAD

**Issue by tudorific** [MscrmTools/XrmToolBox#550]
Hi,

I am trying to create a new connection to our CRM test environment, however, I am constantly getting the 'Unable to Login to Dynamics CRM' error message.

I have tried both setting up the connection through the UI and also a connection string but I get the same result. My connection string is:
ServiceUri=https://<ipaddressofserver>/<organization>;AuthType=IFD;Domain=DEV;UserName=DEV\administrator;Password=test1234;LoginPrompt=Never;

The log shows the following: 

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	1/12/2017 9:01:46 AM  Source	: System.ServiceModel
Method	: ReadResponse
Date	: 1/12/2017
Time	: 9:01:46 AM
Error	: ID3082: The request scope is not valid or is unsupported.
Stack Trace	: at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
```

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	1/12/2017 9:01:46 AM  Unable to Login to Dynamics CRM

Is there something I am missing?

Thanks for the help!

**Comment by tudorific** [comment]
I have also tried leaving the Domain blank in the above connection string but then I get the following error in the log file:

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	1/12/2017 9:33:07 AM  Source	: Microsoft.Xrm.Sdk
Method	: .ctor
Date	: 1/12/2017
Time	: 9:33:07 AM
Error	: Value cannot be null.
Parameter name: securityTokenResponse
Stack Trace	: at Microsoft.Xrm.Sdk.Client.ServiceProxy`1..ctor(IServiceConfiguration`1 serviceConfiguration, SecurityTokenResponse securityTokenResponse)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
```

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #30](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/30) via [**ZenHub**](https://www.zenhub.com/)
