### ISSUE TITLE
Creating connection: Unable to cast object

### ISSUE THREAD

**Issue by chironh** [MscrmTools/XrmToolBox#558]
When creating a new connection, XrmToolbox (**1.2017.1.6**) throws an exception:

```
System.InvalidCastException: Unable to cast object of type 'System.Windows.Forms.ToolStripDropDownButton' to type 'System.Windows.Forms.ToolStripMenuItem'.
   at McTools.Xrm.Connection.WinForms.CrmConnectionStatusBar.newConnectionItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by MscrmTools** [comment]
I guess you are creating a new connection from the bottom left connection menu?

**Comment by MscrmTools** [comment]
Please use connection manager to create a new connection while I fix this issue

**Comment by chironh** [comment]
I guess this cast is wrong:

ToolStripMenuItem toolStripMenuItem = (ToolStripMenuItem)((**ToolStripMenuItem**)sender).OwnerItem;

**Comment by MscrmTools** [comment]
This is not this one, I found the problem and the fix is on its way
