### ISSUE TITLE
Unable to open any connections using version 1.2017.1.10

### ISSUE THREAD

**Issue by mtnmuncher** [MscrmTools/XrmToolBox#561]
See attachment for pop-up when I click 'connect'. I can create the connection. I just cannot open the connection.

1.del MSCRMTools\XrmToolbox folder. I thought it would be better to start anew.
2.open  XrmToolBox 
3.create new connection
4.select  new connection. 
5.connect

Since I could not get the downloaded assembly to work, I then tried running from source. Please see error when running from Visual Studio.

---------------------------
Error
---------------------------
An unexpected error occured: System.InvalidCastException: Unable to cast object of type 'System.Windows.Forms.ToolStripDropDownButton' to type 'System.Windows.Forms.ToolStripMenuItem'.

   at McTools.Xrm.Connection.WinForms.CrmConnectionStatusBar.actionItem_Click(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)

   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   at XrmToolBox.Program.Main(String[] args) in C:\downloads\XrmToolBox-v.1.2017.1.10\XrmToolBox\Program.cs:line 46

One reason can be that at least one file is locked by Windows. Please unlock each locked files or unlock XrmToolBox.zip before extracting its content
---------------------------
OK   
---------------------------
![xrmtoolbox_v1_2017_1_10_connection_error](https://cloud.githubusercontent.com/assets/6696112/22349171/8e88685a-e3dc-11e6-8202-57743b708497.png)

**Comment by MscrmTools** [comment]
Ok, so it happens only when connecting?

Can you connect with the button on the main toolbar waiting for a fix?

**Comment by mtnmuncher** [comment]
Yes, it appears to be isolated to the Connect, located in lower left corner. Connect using main toolbar is successful. Thanks.

**Comment by rajyraman** [comment]
Same behaviour. Able to connect using the "Connect to CRM" button as suggested.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #23](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/23) via [**ZenHub**](https://www.zenhub.com/)
