### ISSUE TITLE
Connection Failure for new Great Britain (.CRM11) D365 environments 

### ISSUE THREAD

**Issue by pspeedy** [MscrmTools/XrmToolBox#626]
There is an issue connecting to any D365 environment that is provisioned with the new Great Britain ***.crm11.dynamics.com url.

Had a similar problem with Scribe which they have fixed so it is an App side problem

Here is an extract of the connection log (this is common across attempts to access many such environments:- (Full file attached)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : No Orgs Found, Searched Online. Region Setting = 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
Method	: HandleReturnMessage
Date	: 05/05/2017
Time	: 08:53:40
Error	: Access is denied.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : No Orgs Found, Searched Online. Region Setting = 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM

[XrmToolBoxConnection.txt](https://github.com/MscrmTools/XrmToolBox/files/978384/XrmToolBoxConnection.txt)

**Comment by MscrmTools** [comment]
A new version is almost ready to ship with support for UK geo

**Comment by pspeedy** [comment]
Nice one 😊  - thanks

Sent from my Windows Phone
________________________________

**Comment by ghasman** [comment]
Im having the same issue please let us know when the update is available

**Comment by MscrmTools** [comment]
Probably early next week, knowing Monday is a day off in France, so you should be able to update your XrmToolBox on Tuesday
