### ISSUE TITLE
Error when trying to restart after update

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#754]
Got this nasty one after updating some plugins.
Accepted the restart prompt, and instead of restarting:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XrmToolBox.PluginsStore.StoreFromPortal.PerformInstallation(PluginUpdates updates, Form storeForm)
   at XrmToolBox.PluginsStore.StoreFormFromPortal.<tsbInstall_Click>b__18_5(Object sbw, DoWorkEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by rappen** [comment]
After manual restart I got this message, that could need some formatting love:
![image](https://user-images.githubusercontent.com/2572253/39231728-4e499652-486b-11e8-9d5d-66336b452752.png)

After clicking OK there, XTB started as expected, but the plugins I first selected to update are still not updated.
Updating them again worked fine.
This time I had no plugins open when updating and restart went fine.
So my guess is that the original problem occurs when plugins are opened and need to be closed before restart.
