### ISSUE TITLE
Tabbing between plugins crash

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#755]
Sometimes you get this crash when CTRL+TAB'ing to switch tool:
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at XrmToolBox.New.PluginForm.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

Unfortunately I don't see any clear pattern when this occurs, but for me it does occur more often than not.

Related to #739

**Comment by MscrmTools** [comment]
Ok, I am using `TabIndex` property to find appropriate tab. Maybe is does not work like I though it was

**Comment by rappen** [comment]
Might be related to floating windows etc...

**Comment by MscrmTools** [comment]
For now, I'm just handling the error. I will see later if it requires more effort to handle this fearure correctly
