### ISSUE TITLE
XRM Tool box issue with CRM 2013 SP1 UR2

### ISSUE THREAD

**Issue by irah2013** [MscrmTools/XrmToolBox#79]
Xrm toolbox is a wonderful tool which i used for long time, in my new project we had CRM 2013 SP1 in which toolbox worked like charm, but when we updated to SP1 UR2 we ended up in having the attached issues while loading entities for any request.

![capture](https://cloud.githubusercontent.com/assets/11574556/6754648/ea16d828-cf43-11e4-866d-7678ae72d3c3.JPG)

**Comment by MscrmTools** [comment]
Hi,
I don't have any environment in CRM 2013 SP1 UR2 available currently so I can't test anything...

Would you be able to take a CRM Server trace (using CrmDiagTool2011 for example) in Error mode when this error occurs in XrmToolBox? We should get a more detailed error message.

**Comment by irah2013** [comment]
Below is the error i can get from Event Viewer. I can't run the CRMDiagTool at this point since have some limitations with server.

The Web Service plug-in failed in OrganizationId: e0546e2a-a3c0-e411-80c3-00155d0a1e19; SdkMessageProcessingStepId: e309ed1a-7bee-4ae0-a6f4-f11a6330cd5e; EntityName: none; Stage: 30; MessageName: RetrieveAllEntities; AssemblyName: Microsoft.Crm.Extensibility.InternalOperationPlugin, Microsoft.Crm.ObjectModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35; ClassName: Microsoft.Crm.Extensibility.InternalOperationPlugin; Exception: Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Web.Services.Protocols.LogicalMethodInfo.Invoke(Object target, Object[] values)
   at Microsoft.Crm.Extensibility.InternalOperationPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Extensibility.V5PluginProxyStep.ExecuteInternal(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
Inner Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Crm.MetadataService.Sdk.TypeMaps.PlatformToXrmEntityMetadataTypeMap' threw an exception.
   at Microsoft.Crm.Sdk.Metadata.EntityConverter.SetupEntityMetadataProperties(EntityFilters entityFilters, MetadataConversionContext context)
   at Microsoft.Crm.Sdk.Metadata.EntityConverter.ToXrmEntityMetadataArray(EntityFilters entityFilters, MetadataConversionContext conversionContext)
   at Microsoft.Crm.Sdk.Metadata.MetadataServiceProvider.RetrieveAllEntities(EntityFilters metadataItems, Boolean retrieveAsIfPublished, ExecutionContext context, String& timestamp)
Inner Exception: System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> Microsoft.Xrm.Sdk.Metadata.EntityMetadata.get_IsStateModelAware()'.
   at Microsoft.Crm.MetadataService.Sdk.TypeMaps.PlatformToXrmEntityMetadataTypeMap.InitializeMap()
   at Microsoft.Crm.MetadataService.Sdk.TypeMaps.PlatformToXrmEntityMetadataTypeMap..cctor()
.

**Comment by MscrmTools** [comment]
I just hope Microsoft did not removed legacy metadata request...
Can you try if fls bulk updater plugin works? It uses the metadataqueryexpression instead of legacy metadata request. If this works, I think I'll have to change all metadata retrievals...

**Comment by irah2013** [comment]
FLS bulk updater Worked perfectly!!!! its bad that we cant use it just because we updated to latest one :(

**Comment by MscrmTools** [comment]
Just built a CRM 2013 sp1 ur2 server.

Everything is working as expected for me. I guess something is wrong with your deployment

**Comment by irah2013** [comment]
For me fls bulk updator works as expected. But for all others it fails during retrieve all entities.. Let me download the source code and try to debug through.

MscrmTools <notifications@github.com> wrote:



Just built a CRM 2013 sp1 ur2 server.

Everything is working as expected for me. I guess something is wrong with your deployment

-
Reply to this email directly or view it on GitHub<https://github.com/MscrmTools/XrmToolBox/issues/79#issuecomment-84332828>.

Hitachi Solutions America is a company registered in the United States with registration number 3127998 whose registered office is at 851 Traeger Ave., Suite 200, San Bruno, CA 94066. This e-mail is intended solely for the person or entity to which it is addressed and may contain confidential and/or privileged information. Any review, dissemination, copying, printing or other use of this e-mail by persons or entities other than the addressee is prohibited. If you have received this e-mail in error, please contact the sender immediately and delete the material from any computer.

**Comment by MscrmTools** [comment]
As I didn't get any news from you @irah2013 , I'm closing this issue.

Do not hesitate to reopen it if needed

**Comment by irah2013** [comment]
Hi @MscrmTools ,

This was an issue with the environment, the Assemblies were not registered to GAC properly which was causing the issue. Now the Tool works well!! Thanks again
