### ISSUE TITLE
Not able to connect to CRM 2011 using xrmtoolbox latest version v1.2018.07.28

### ISSUE THREAD

**Issue by Poonam1910** [MscrmTools/XrmToolBox#799]
Hi All,
I am unable to connect with the new connection manager in latest version to crm 5 (cloud and on premises)  Using the below step
![image](https://user-images.githubusercontent.com/42572785/44396537-c5021100-a56f-11e8-82ad-2b56cbd9a492.png)
![image](https://user-images.githubusercontent.com/42572785/44396895-e57e9b00-a570-11e8-9bce-e7a540363e97.png)

The same configuration is used to connect to visual studio. and its working fine there. Even I tried using connection string 
AuthType=AD;url=https://xxx.crm5.dynamics.com/;Domain=Organisation Unique name;Username=XXX@xxx.com;Password=XXX tried both AD and IFD. But no luck

I could find the APP id in customization screen in crm . Is this APP id is same as Azure app ID. If yes. Where could we find the Redirect URI.

Please assist on this issue. Thanks in advance.

**Comment by Poonam1910** [comment]
Please find the log for your reference. Please help me if you have an idea. I am able to connect to crm online  and using visual studio 2013 and also plugin registration tool. Only  Xrm tool box not able to connect.
Please find log for your reference, which shows' Please provide username even though its available.

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/8/2018 6:30:16 PM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/8/2018 6:30:24 PM  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 23/8/2018
Time	: 6:30:24 PM
Error	: The username is not provided. Specify username in ClientCredentials.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.ClientCredentialsSecurityTokenManager.CreateSecurityTokenProvider(SecurityTokenRequirement tokenRequirement, Boolean disableInfoCard)
   at System.ServiceModel.Security.SecurityProtocol.AddSupportingTokenProviders(SupportingTokenParameters supportingTokenParameters, Boolean isOptional, IList`1 providerSpecList)
   at System.ServiceModel.Security.SecurityProtocol.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.ClientSecurityChannel`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateTokenWithOrgIdForCrm(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

**Comment by MscrmTools** [comment]
Connection string should be something like

AuthType=Office365;url=https://xxx.crm5.dynamics.com/;Username=XXX@xxx.com;Password=XXX

**Comment by MscrmTools** [comment]
Did you solve your issue with a correct connection string?

**Comment by Poonam1910** [comment]
Issue has been fixed. Thanks
