### ISSUE TITLE
Cannot connect to Dynamics 365 instance

### ISSUE THREAD

**Issue by sabrina-lanzoni** [MscrmTools/XrmToolBox#810]
Hello everyone,
unfortunately I am not able to connect to my Dynamics 365 instance at all: I put the address of my CRM instance and my credentials in the format <domain>\<username>, and this is the error that I get:

_Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	14.09.2018 08:23:51  Source	: Microsoft.Xrm.Sdk
Method	: Assert
Date	: 14.09.2018
Time	: 08:23:51
Error	: clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!
Stack Trace	: at Microsoft.Xrm.Sdk.ClientExceptionHelper.Assert(Boolean condition, String message)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.GetIdentityProvider(ClientCredentials clientCredentials)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	14.09.2018 08:23:51  Unable to Login to Dynamics CRM_

Could you please take a look at this issue?

Thanks a lot in advance!

**Comment by MscrmTools** [comment]
Is it CRM online? If yes, you should put your email address for username

**Comment by sabrina-lanzoni** [comment]
Thanks a lot for the info, that solved the issue!

👍

**Comment by tclancy** [comment]
I see this error when trying to use an application id and client secret as the parameters in place of username and password for an automated pipeline script. [This should theoretically work](https://stackoverflow.com/a/55583672/7376) but doesn't seem to for any of our 3 urls when I run `connect-crmonline -Credential $cred -ServerUrl xxx.crm.dynamics.com`.
