### ISSUE TITLE
NullReferenceException on Open Project Home Page for Plugin

### ISSUE THREAD

**Issue by altmank** [MscrmTools/XrmToolBox#812]
From the Plugins tab in v1.2018.7.18, I right click on "Code Now" Plugin in the list > Open Project Home Page, the below error is shown.

`
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at XrmToolBox.New.NewForm.PluginsForm_OpenPluginProjectUrlRequested(Object sender, PluginEventArgs e)
   at System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by MscrmTools** [comment]
Thanks for reporting
