### ISSUE TITLE
Hi While Opening the XRM tool box i got the wired behavior. I am getting the empty Screen while it is opened. Please find the screen shot for reference.

### ISSUE THREAD

**Issue by manas3487** [MscrmTools/XrmToolBox#819]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by manas3487** [comment]
![xrm](https://user-images.githubusercontent.com/35729553/47077699-27e5f080-d21f-11e8-8c60-ae3f1a1b72b3.PNG)

**Comment by manas3487** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at XrmToolBox.New.NewForm.ShowStartPage()
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1665.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2018.7.28
    Win32 Version: 1.2018.7.28
    CodeBase: file:///D:/XRM/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1652.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2018.7.28
    Win32 Version: 1.2018.7.28
    CodeBase: file:///D:/XRM/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.10586.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2018.7.28
    Win32 Version: 1.2018.7.28
    CodeBase: file:///D:/XRM/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.14.0.832
    Win32 Version: 2.14.0.832
    CodeBase: file:///D:/XRM/NuGet.Core.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///D:/XRM/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2018.7.19
    Win32 Version: 1.2018.7.19
    CodeBase: file:///D:/XRM/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2018.7.19
    Win32 Version: 1.2018.7.19
    CodeBase: file:///D:/XRM/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0002.0165
    CodeBase: file:///D:/XRM/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0002.0165
    CodeBase: file:///D:/XRM/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0002.0165
    CodeBase: file:///D:/XRM/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.931
    CodeBase: file:///D:/XRM/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///D:/XRM/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///D:/XRM/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///D:/XRM/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///D:/XRM/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/XRM/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
BDK.XrmToolBox.UserAuditViewer
    Assembly Version: 1.2017.11.1
    Win32 Version: 1.2017.11.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.USERAUDITVIEWER.DLL
----------------------------------------
Cube.XRMToolBox.RecordCounter
    Assembly Version: 1.2017.2.1
    Win32 Version: 1.2017.2.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CUBE.XRMTOOLBOX.RECORDCOUNTER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2018.3.5
    Win32 Version: 1.2018.3.5
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2018.3.3
    Win32 Version: 1.2018.3.3
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
DocumentFormat.OpenXml
    Assembly Version: 2.5.5631.0
    Win32 Version: 2.5.5631.0
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DOCUMENTFORMAT.OPENXML.DLL
----------------------------------------
EPPlus
    Assembly Version: 4.0.5.0
    Win32 Version: 4.0.5.0
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/EPPLUS.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2018.3.8
    Win32 Version: 1.2018.3.8
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2018.7.2
    Win32 Version: 1.2018.7.2
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2018.3.2
    Win32 Version: 1.2018.3.2
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2018.7.10
    Win32 Version: 1.2018.7.10
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MscrmTools.DataUsageInspector
    Assembly Version: 1.2016.9.20
    Win32 Version: 1.2016.9.20
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DATAUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2018.4.3
    Win32 Version: 1.2018.4.3
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.12.3
    Win32 Version: 1.2017.12.3
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2018.7.9
    Win32 Version: 1.2018.7.9
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2018.3.7
    Win32 Version: 1.2018.3.7
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2018.6.8
    Win32 Version: 1.2018.6.8
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2018.6.5
    Win32 Version: 1.2018.6.5
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2018.6.23
    Win32 Version: 1.2018.6.23
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2017.12.6
    Win32 Version: 1.2017.12.6
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2018.1.2
    Win32 Version: 1.2018.1.2
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2018.7.11
    Win32 Version: 1.2018.7.11
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2018.4.6
    Win32 Version: 1.2018.4.6
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2018.7.8
    Win32 Version: 1.2018.7.8
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.4.4
    Win32 Version: 1.2017.4.4
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly Version: 2.2018.7.4
    Win32 Version: 2.2018.7.4
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities.Tooling
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.TOOLING.DLL
----------------------------------------
Norriq.XrmToolBox.YourConnectionStringBuilt
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/NORRIQ.XRMTOOLBOX.YOURCONNECTIONSTRINGBUILT.DLL
----------------------------------------
Norriq.XrmToolBox.YourEntityAttributeMappingsCustomized
    Assembly Version: 1.0.17102.2
    Win32 Version: 1.0.17102.2
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/NORRIQ.XRMTOOLBOX.YOURENTITYATTRIBUTEMAPPINGSCUSTOMIZED.DLL
----------------------------------------
Ryr.ExcelExport
    Assembly Version: 2.4.0.0
    Win32 Version: 2.4.0
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.EXCELEXPORT.DLL
----------------------------------------
XrmToolBox Advanced FetchXML Tester
    Assembly Version: 1.0.0.4
    Win32 Version: 1.0.0.4
    CodeBase: file:///D:/USERS/MANASKUMAR.G/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRMTOOLBOX%20ADVANCED%20FETCHXML%20TESTER.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1665.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1665.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1652.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1658.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1658.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1665.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1665.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by manas3487** [comment]
The above is the error message when i try to open it

**Comment by MscrmTools** [comment]
Can you try to reset your XrmToolBox installation? 
https://www.xrmtoolbox.com/documentation/for-users/reset-xrmtoolbox-installation/

**Comment by manas3487** [comment]
Hi I am unable to find the user name folder in users can you please help me
to make this working

**Comment by MscrmTools** [comment]
No, I can't help you if your profile is not stored in Users, then I don't know where your IT team has moved it
