### ISSUE TITLE
Uninstalling tool throws exception

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#821]
Uninstalled a tool from the Plugins Store, and got this exception:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.Restart()
   at XrmToolBox.PluginsStore.StoreFromPortal.PerformUninstallation(PluginDeletions deletions)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
```
No more info about it unfortunately.

**Comment by rappen** [comment]
Just uninstalled another tool, got the exact same error again.
v1.2018.10.29
