### ISSUE TITLE
Connecting to CRM

### ISSUE THREAD

**Issue by gaharlan** [MscrmTools/XrmToolBox#842]
Updated to version: 1.2019.2.30
Now unable to connect to CRM
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2/28/2019 11:41:27 AM  Unable to login to Dynamics CRM, Error was : An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 2/28/2019
Time	: 11:41:27 AM
Error	: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 2/28/2019
Time	: 11:41:27 AM
Error	: ID3242: The security token could not be authenticated or authorized.
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2/28/2019 11:41:27 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2/28/2019 11:41:27 AM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 2/28/2019
Time	: 11:41:27 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Comment by MscrmTools** [comment]
Apparently, the error should not come from the update.
The error message indicates something is rejected by the CRM organization.
I would ensure credentials are correct and computer time is synced

**Comment by apstevenson** [comment]
I think I am having the same issue, although I can't find the logs. I cannot connect to any of my previously setup connections. The connections were working before the update.

**Comment by apstevenson** [comment]
I rebooted but that did not work. So I manually downgraded to test and the connections work again.

**Comment by MscrmTools** [comment]
What kind of connection is it? Online? OnPrem? I did connect to Online. Did not test OnPrem yet

**Comment by gaharlan** [comment]
Onprem



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by dirasmitabasu** [comment]
I have the same issue. I removed a connection and tried to add a new connection, same behavior.

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	28-Feb-19 14:13:49  Unable to login to Dynamics CRM, Error was : The value could not be added to the collection, as the collection already contains an item of the same type: 'Microsoft.Xrm.Sdk.Client.ProxyTypesBehavior'. This collection only supports one instance of each type.
Parameter name: item
Source	: System.ServiceModel
Method	: InsertItem
Date	: 28-Feb-19
Time	: 14:13:49
Error	: The value could not be added to the collection, as the collection already contains an item of the same type: 'Microsoft.Xrm.Sdk.Client.ProxyTypesBehavior'. This collection only supports one instance of each type.
Parameter name: item
Stack Trace	: at System.Collections.Generic.KeyedByTypeCollection`1.InsertItem(Int32 index, TItem item)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	28-Feb-19 14:13:49  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	28-Feb-19 14:13:49  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 28-Feb-19
Time	: 14:13:49
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Please fix this, I can't use the toolbox at all after the update**

**Comment by MscrmTools** [comment]
For the last error mentioned, it seems to be more relative to a faulty plugin

**Comment by riccaceres** [comment]
I have the same issue on an IFD on-prem instance. For the time being we've reverted to the previous toolbox version.

**Comment by dirasmitabasu** [comment]
> I have the same issue on an IFD on-prem instance. For the time being we've reverted to the previous toolbox version.

I tried to revert, but I want to use the Easy Translator and it doesn't seem to support any other release.

**Comment by dirasmitabasu** [comment]
> I have the same issue on an IFD on-prem instance. For the time being we've reverted to the previous toolbox version.

I have cl

> For the last error mentioned, it seems to be more relative to a faulty plugin

I cleared all plugins and then started the toolbox, the error persists.

**Comment by MscrmTools** [comment]
Ok can’t tell why everything works well on my side. I have report from other users with working updated version

**Comment by MscrmTools** [comment]
For easy translator, it is compatible with previous version

**Comment by MscrmTools** [comment]
Ok, I can reproduce for an OnPremise organization.
Let me debug that

**Comment by MscrmTools** [comment]
Until I found the cause of the issue, you can download the previous version [here](https://github.com/MscrmTools/XrmToolBox/releases/download/v.1.2018.10.29/XrmToolbox.zip)

**Comment by MscrmTools** [comment]
Ok everyone, I got the confirmation from Microsoft there was a bug in one of their version. Let me update to their latest bit and we will be good!

**Comment by dirasmitabasu** [comment]
> Until I found the cause of the issue, you can download the previous version [here](https://github.com/MscrmTools/XrmToolBox/releases/download/v.1.2018.10.29/XrmToolbox.zip)

Thanks. I was able to make it work with this version.

**Comment by MscrmTools** [comment]
I released a new version (1.2019.2.32) that should work too

**Comment by gaharlan** [comment]
Thank you, will give it a try



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by riccaceres** [comment]
The new version fixed the issue on my end. Thanks for the update.

**Comment by MscrmTools** [comment]
I'm glad it fixes your issue

**Comment by jazmatician** [comment]
Can we get this bug fix in the developer nuget package? The latest package is 1.2019.2.30.
