### ISSUE TITLE
Unable to connect to CRM 2016 instance

### ISSUE THREAD

**Issue by Jamizzle93** [MscrmTools/XrmToolBox#869]
Hello all,

Firstly, I'd like to thank the developers for developing the XrmToolBox! It seems like a great tool.
However, I am having problems trying to connect to my solution using the tool.

I am attempting to use the Connection Wizard. I enter my organisation URL as **https://raspberrytest.mycrmhosted.net** and select IFD as No. I then enter my domain, username and password. Afterwards, it tries to connect and fails. I have included the error log below.

```Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/06/2019 09:58:23  Initialize CRM connection Started - AuthType: AD
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/06/2019 09:58:23  Discovery URI is = https://merseyrailtest.mycrmhosted.net:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/06/2019 09:58:23  DiscoverOrganizations - Initializing Discovery Server Object with https://merseyrailtest.mycrmhosted.net/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/06/2019 09:58:23  DiscoverOrganizations - attempting to connect to CRM server @ https://merseyrailtest.mycrmhosted.net/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/06/2019 09:58:23  DiscoverOrganizations - created CRM server proxy configuration for https://merseyrailtest.mycrmhosted.net/XRMServices/2011/Discovery.svc - duration: 00:00:00.4101555
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/06/2019 09:58:23  DiscoverOrganizations - proxy requiring authentication type : Federation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/06/2019 09:58:23  DiscoverOrganizations - Authenticated via Federation. Auth Elapsed:00:00:00.0515059
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/06/2019 09:58:23  DiscoverOrganizations - service proxy created - total create duration: 00:00:00.4622535
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/06/2019 09:58:23  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/06/2019 09:58:23  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Source	: Not Provided
Method	: Not Provided
Date	: 11/06/2019
Time	: 09:58:23
Error	: ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/06/2019 09:58:23  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 11/06/2019
Time	: 09:58:23
Error	: The content type text/html; charset=UTF-8 of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<HTML><HEAD><link rel="alternate" type="text/xml" href="https://discover.mycrmhosted.net/XRMServices/2011/Discovery.svc?disco"/><STYLE type="text/css">#content{ FONT-SIZE: 0.7em; PADDING-BOTTOM: 2em; MARGIN-LEFT: 30px}BODY{MARGIN-TOP: 0px; MARGIN-LEFT: 0px; COLOR: #000000; FONT-FAMILY: Verdana; BACKGROUND-COLOR: white}P{MARGIN-TOP: 0px; MARGIN-BOTTOM: 12px; COLOR: #000000; FONT-FAMILY: Verdana}PRE{BORDER-RIGHT: #f0f0e0 1px solid; PADDING-RIGHT: 5px; BORDER-TOP: #f0f0e0 1px solid; MARGIN-TOP: -5px; PADDING-LEFT: 5px; FONT-SIZE: 1.2em; PADDING-BOTTOM: 5px; BORDER-LEFT: #f0f0e0 1px solid; PADDING-TOP: 5px; BORDER-BOTTOM: #f0f0e0 1px solid; FONT-FAMILY: Courier New; BACKGROUND-COLOR: #e5e5cc}.heading1{MARGIN-TOP: 0px; PADDING-LEFT: 15px; FONT-WEIGHT: normal; FONT-SIZE: 26px; MARGIN-BOTTOM: 0px; PADDING-BOTTOM: 3px; MARGIN-LEFT: -30px; WIDTH: 100%; COLOR: #ffffff; PADDING-TOP: 10px; FONT-FAMILY: Tahoma; BACKGROUND-COLOR: #003366}.intro{MARGIN-LEFT: -15px}</STYLE><TITLE>DiscoveryService Service</TITLE></HEAD><BODY>'.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/06/2019 09:58:23  Unable to login to Dynamics CRM, Error was : The content type text/html; charset=UTF-8 of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<HTML><HEAD><link rel="alternate" type="text/xml" href="https://discover.mycrmhosted.net/XRMServices/2011/Discovery.svc?disco"/><STYLE type="text/css">#content{ FONT-SIZE: 0.7em; PADDING-BOTTOM: 2em; MARGIN-LEFT: 30px}BODY{MARGIN-TOP: 0px; MARGIN-LEFT: 0px; COLOR: #000000; FONT-FAMILY: Verdana; BACKGROUND-COLOR: white}P{MARGIN-TOP: 0px; MARGIN-BOTTOM: 12px; COLOR: #000000; FONT-FAMILY: Verdana}PRE{BORDER-RIGHT: #f0f0e0 1px solid; PADDING-RIGHT: 5px; BORDER-TOP: #f0f0e0 1px solid; MARGIN-TOP: -5px; PADDING-LEFT: 5px; FONT-SIZE: 1.2em; PADDING-BOTTOM: 5px; BORDER-LEFT: #f0f0e0 1px solid; PADDING-TOP: 5px; BORDER-BOTTOM: #f0f0e0 1px solid; FONT-FAMILY: Courier New; BACKGROUND-COLOR: #e5e5cc}.heading1{MARGIN-TOP: 0px; PADDING-LEFT: 15px; FONT-WEIGHT: normal; FONT-SIZE: 26px; MARGIN-BOTTOM: 0px; PADDING-BOTTOM: 3px; MARGIN-LEFT: -30px; WIDTH: 100%; COLOR: #ffffff; PADDING-TOP: 10px; FONT-FAMILY: Tahoma; BACKGROUND-COLOR: #003366}.intro{MARGIN-LEFT: -15px}</STYLE><TITLE>DiscoveryService Service</TITLE></HEAD><BODY>'.
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 11/06/2019
Time	: 09:58:23
Error	: The content type text/html; charset=UTF-8 of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<HTML><HEAD><link rel="alternate" type="text/xml" href="https://discover.mycrmhosted.net/XRMServices/2011/Discovery.svc?disco"/><STYLE type="text/css">#content{ FONT-SIZE: 0.7em; PADDING-BOTTOM: 2em; MARGIN-LEFT: 30px}BODY{MARGIN-TOP: 0px; MARGIN-LEFT: 0px; COLOR: #000000; FONT-FAMILY: Verdana; BACKGROUND-COLOR: white}P{MARGIN-TOP: 0px; MARGIN-BOTTOM: 12px; COLOR: #000000; FONT-FAMILY: Verdana}PRE{BORDER-RIGHT: #f0f0e0 1px solid; PADDING-RIGHT: 5px; BORDER-TOP: #f0f0e0 1px solid; MARGIN-TOP: -5px; PADDING-LEFT: 5px; FONT-SIZE: 1.2em; PADDING-BOTTOM: 5px; BORDER-LEFT: #f0f0e0 1px solid; PADDING-TOP: 5px; BORDER-BOTTOM: #f0f0e0 1px solid; FONT-FAMILY: Courier New; BACKGROUND-COLOR: #e5e5cc}.heading1{MARGIN-TOP: 0px; PADDING-LEFT: 15px; FONT-WEIGHT: normal; FONT-SIZE: 26px; MARGIN-BOTTOM: 0px; PADDING-BOTTOM: 3px; MARGIN-LEFT: -30px; WIDTH: 100%; COLOR: #ffffff; PADDING-TOP: 10px; FONT-FAMILY: Tahoma; BACKGROUND-COLOR: #003366}.intro{MARGIN-LEFT: -15px}</STYLE><TITLE>DiscoveryService Service</TITLE></HEAD><BODY>'.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/06/2019 09:58:23  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/06/2019 09:58:23  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 11/06/2019
Time	: 09:58:23
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================
```

Any suggestions would be much appreciated and I'd be happy to try and answer any questions to help get this solved.

Many thanks in advance to anyone who is willing to help! :)

**Comment by fuattatar** [comment]
Hi Jamizzle93,
Can you try open crm discovery service on your browser? There might be issue with crm discovery service. You can find discovery service url as described below: 
Login Crm
Setting>Customization>Developer Resources>Discovery service
Copy Discovery Service Url
Paste it in your browser
See if its working or there is an issue with discovery service

**Comment by Jamizzle93** [comment]
Hi @fuattatar 
Thanks for your reply. It seems to work.


> Hi Jamizzle93,
> Can you try opening crm discovery service on your browser? There might be issue with crm discovery service. You can find discovery service url as described below:
> Login Crm
> Setting>Customization>Developer Resources>Discovery service
> Copy Discovery Service Url
> Paste it in your browser
> See if its working or there is an issue with discovery service

Hi @fuattatar 
It seems to work as I would expect.
![DiscoveryService Service](https://user-images.githubusercontent.com/5894967/59917600-3d4c9380-941a-11e9-93f1-67cd4f5f57f5.PNG)

**Comment by fuattatar** [comment]
Is your organization using IFD?

**Comment by Jamizzle93** [comment]
> Is your organization using IFD?

No, the organization is not using IFD.

**Comment by fuattatar** [comment]
If your login screen seems like that
![1](https://user-images.githubusercontent.com/2419809/59929377-60db0280-9449-11e9-9289-51433f93e518.PNG)
Its IFD.

**Comment by Jamizzle93** [comment]
> If your login screen seems like that
> ![1](https://user-images.githubusercontent.com/2419809/59929377-60db0280-9449-11e9-9289-51433f93e518.PNG)
> Its definitly IFD.

Okay, thank you very much for your response.
I believe it may be using IFD. Our sign in screen looks like this:

![CRMSignInScreen](https://user-images.githubusercontent.com/5894967/59929604-12be0300-9439-11e9-948a-aeb88726cebf.PNG)

**Comment by fuattatar** [comment]
You are welcome. You can try to connect your organization with IFD option in xrmtoolbox.

**Comment by Jamizzle93** [comment]
> You are welcome. You can try to connect your organization with IFD option in xrmtoolbox.

Hi @fuattatar 
Thanks for your suggestion.
Connecting with the IFD option still doesn't work. I am still seeing this error:
`Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	24/06/2019 09:04:52  Initialize CRM connection Started - AuthType: Claims
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	24/06/2019 09:04:52  Discovery URI is = https://raspberrytest.mycrmhosted.net:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	24/06/2019 09:04:52  DiscoverOrganizations - Initializing Discovery Server Object with https://raspberrytest.mycrmhosted.net/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	24/06/2019 09:04:52  DiscoverOrganizations - attempting to connect to CRM server @ https://raspberrytest.mycrmhosted.net/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	24/06/2019 09:04:53  DiscoverOrganizations - created CRM server proxy configuration for https://raspberrytest.mycrmhosted.net/XRMServices/2011/Discovery.svc - duration: 00:00:00.8197778
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	24/06/2019 09:04:53  DiscoverOrganizations - proxy requiring authentication type : Federation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	24/06/2019 09:04:53  Unable to login to Dynamics CRM, Error was : An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 24/06/2019
Time	: 09:04:53
Error	: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 24/06/2019
Time	: 09:04:53
Error	: At least one security token in the message could not be validated.
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	24/06/2019 09:04:53  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	24/06/2019 09:04:53  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 24/06/2019
Time	: 09:04:53
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

`

**Comment by fuattatar** [comment]
Hi @Jamizzle93 . I' am not sure. Your CRM organization may have invalid configuration.

**Comment by MscrmTools** [comment]
Still an issue? Please comment if so
