### ISSUE TITLE
Error When Trying To Connect To CRM

### ISSUE THREAD

**Issue by JamesStuder** [MscrmTools/XrmToolBox#907]
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:40 AM  Initialize CRM connection Started - AuthType: Office365
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:40 AM  Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:40 AM  DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:40 AM  DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:44 AM  DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:03.5817646
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:44 AM  DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:46 AM  DiscoverOrganizations - Authenticated via OnlineFederation. Auth Elapsed:00:00:01.8343085
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:46 AM  DiscoverOrganizations - service proxy created - total create duration: 00:00:05.4179519
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  DiscoverOrganizations - Discovery Server Get Orgs Call Complete - Elapsed:00:00:02.6094490
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  Found 17 Org(s)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  Looking for Organization = msf-nyc-crm-sdb in the results from CRM's Discovery server list.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  found User Org = msf-nyc-crm-sdb in results
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:48 AM  DiscoveryServer indicated organization service location = https://msf-nyc-crm-sdb.api.crm4.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  Organization Service URI is = https://msf-nyc-crm-sdb.api.crm4.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:48 AM  ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  ConnectAndInitCrmOrgService - Requesting connection to Organization with CRM Version: 9.1.0.10329
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:48 AM  ConnectAndInitCrmOrgService - Using ISerivceManagement
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:48 AM  ConnectAndInitCrmOrgService - attempting to connect to CRM server @ https://msf-nyc-crm-sdb.api.crm4.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:49 AM  ConnectAndInitCrmOrgService - created CRM server proxy configuration for https://msf-nyc-crm-sdb.api.crm4.dynamics.com/XRMServices/2011/Organization.svc - duration: 00:00:00.9389567
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:49 AM  ConnectAndInitCrmOrgService - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:50 AM  ConnectAndInitCrmOrgService - Authenticated via OnlineFederation. Auth Elapsed:00:00:00.4496182
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/20/2019 8:37:50 AM  ConnectAndInitCrmOrgService - service proxy created - total create duration: 00:00:01.3939214
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:50 AM  ConnectAndInitCrmOrgService - Proxy created, total elapsed time: 00:00:01.3961073
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:50 AM  User Org (orgede08d13) found in Discovery Server EMEA
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	11/20/2019 8:37:50 AM  Beginning Validation of CRM Connection. RequestID: f0f124e5-b275-40c9-931e-0595b3430cdb
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/20/2019 8:37:50 AM  Failed to Executed Command - WhoAmIRequest : RequestId=f0f124e5-b275-40c9-931e-0595b3430cdb : total duration: 00:00:00.1072453
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/20/2019 8:37:50 AM  Failed to Executed Command - WhoAmIRequest : RequestId=f0f124e5-b275-40c9-931e-0595b3430cdb : total duration: 00:00:00.1072453
Source	: Not Provided
Method	: Not Provided
Date	: 11/20/2019
Time	: 8:37:50 AM
Error	: Failed to Executed Command - WhoAmIRequest : RequestId=f0f124e5-b275-40c9-931e-0595b3430cdb : total duration: 00:00:00.1072453
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/20/2019 8:37:50 AM  ************ Exception - Failed to lookup current user
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 11/20/2019
Time	: 8:37:50 AM
Error	: A proxy type with the name pluginassembly has been defined by another assembly. Current type: Carfup.XTBPlugins.Entities.PluginAssembly, Carfup.XTBPlugins.DeltaStepsBetweenEnvironments, Version=1.2019.11.11, Culture=neutral, PublicKeyToken=null, Existing type: PluginAssembly, adesso_XTB_Plugins.DocumentTemplateExport, Version=17.8.2018.3, Culture=neutral, PublicKeyToken=null
Parameter name: pluginassembly
Stack Trace	: Server stack trace: 
   at Microsoft.Xrm.Sdk.AppDomainBasedKnownProxyTypesProvider.AddTypeMapping(Assembly assembly, Type type, String proxyName)
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.LoadKnownTypes(Assembly assembly)
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.RegisterAssembly(Assembly assembly)
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.InitializeLoadedAssemblies()
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.GetInstance(Boolean supportIndividualAssemblies)
   at Microsoft.Xrm.Sdk.ProxySerializationSurrogate.System.Runtime.Serialization.IDataContractSurrogate.GetObjectToSerialize(Object obj, Type targetType)
   at System.Runtime.Serialization.DataContractSerializer.SurrogateToDataContractType(IDataContractSurrogate dataContractSurrogate, Object oldObj, Type surrogatedDeclaredType, Type& objType)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameterPart(XmlDictionaryWriter writer, PartInfo part, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameter(XmlDictionaryWriter writer, PartInfo part, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameters(XmlDictionaryWriter writer, PartInfo[] parts, Object[] parameters)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeBody(XmlDictionaryWriter writer, MessageVersion version, String action, MessageDescription messageDescription, Object returnValue, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.SerializeBodyContents(XmlDictionaryWriter writer, MessageVersion version, Object[] parameters, Object returnValue, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.OperationFormatterMessage.OperationFormatterBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Security.SecurityAppliedMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Security.SecurityAppliedMessage.OnWriteMessage(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BufferedMessageWriter.WriteMessage(Message message, BufferManager bufferManager, Int32 initialOffset, Int32 maxSizeQuota)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessage(Message message, Int32 maxMessageSize, BufferManager bufferManager, Int32 messageOffset)
   at System.ServiceModel.Channels.HttpOutput.SerializeBufferedMessage(Message message, Boolean shouldRecycleBuffer)
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetWhoAmIDetails(IOrganizationService crmService, Guid trackingID)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/20/2019 8:37:50 AM  Unable to connect to CRM: A proxy type with the name pluginassembly has been defined by another assembly. Current type: Carfup.XTBPlugins.Entities.PluginAssembly, Carfup.XTBPlugins.DeltaStepsBetweenEnvironments, Version=1.2019.11.11, Culture=neutral, PublicKeyToken=null, Existing type: PluginAssembly, adesso_XTB_Plugins.DocumentTemplateExport, Version=17.8.2018.3, Culture=neutral, PublicKeyToken=null
Parameter name: pluginassembly
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 11/20/2019
Time	: 8:37:50 AM
Error	: A proxy type with the name pluginassembly has been defined by another assembly. Current type: Carfup.XTBPlugins.Entities.PluginAssembly, Carfup.XTBPlugins.DeltaStepsBetweenEnvironments, Version=1.2019.11.11, Culture=neutral, PublicKeyToken=null, Existing type: PluginAssembly, adesso_XTB_Plugins.DocumentTemplateExport, Version=17.8.2018.3, Culture=neutral, PublicKeyToken=null
Parameter name: pluginassembly
Stack Trace	: Server stack trace: 
   at Microsoft.Xrm.Sdk.AppDomainBasedKnownProxyTypesProvider.AddTypeMapping(Assembly assembly, Type type, String proxyName)
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.LoadKnownTypes(Assembly assembly)
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.RegisterAssembly(Assembly assembly)
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.InitializeLoadedAssemblies()
   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.GetInstance(Boolean supportIndividualAssemblies)
   at Microsoft.Xrm.Sdk.ProxySerializationSurrogate.System.Runtime.Serialization.IDataContractSurrogate.GetObjectToSerialize(Object obj, Type targetType)
   at System.Runtime.Serialization.DataContractSerializer.SurrogateToDataContractType(IDataContractSurrogate dataContractSurrogate, Object oldObj, Type surrogatedDeclaredType, Type& objType)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameterPart(XmlDictionaryWriter writer, PartInfo part, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameter(XmlDictionaryWriter writer, PartInfo part, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameters(XmlDictionaryWriter writer, PartInfo[] parts, Object[] parameters)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeBody(XmlDictionaryWriter writer, MessageVersion version, String action, MessageDescription messageDescription, Object returnValue, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.SerializeBodyContents(XmlDictionaryWriter writer, MessageVersion version, Object[] parameters, Object returnValue, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.OperationFormatterMessage.OperationFormatterBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Security.SecurityAppliedMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Security.SecurityAppliedMessage.OnWriteMessage(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BufferedMessageWriter.WriteMessage(Message message, BufferManager bufferManager, Int32 initialOffset, Int32 maxSizeQuota)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessage(Message message, Int32 maxMessageSize, BufferManager bufferManager, Int32 messageOffset)
   at System.ServiceModel.Channels.HttpOutput.SerializeBufferedMessage(Message message, Boolean shouldRecycleBuffer)
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetWhoAmIDetails(IOrganizationService crmService, Guid trackingID)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/20/2019 8:37:50 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/20/2019 8:37:50 AM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 11/20/2019
Time	: 8:37:50 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Comment by JamesStuder** [comment]
This is happening on latest release and latest pre-release.  Rolling back to latest stable build, connection works.

**Comment by JamesStuder** [comment]
This is not an issue with CrmToolBox but a plugin by Clement.  I removed all 4 plugins from Clement and the issue went away.
