### ISSUE TITLE
Not able to connect to CRM online organization with XRM toolbox. Getting error as "An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail."

### ISSUE THREAD

**Issue by ansabha** [MscrmTools/XrmToolBox#912]
Steps to Reproduce the issue:-
==========================================
1. Open Xrm tool  Box
2. Click on New connection 
3. Select Connection wizard as an option 
4. Enter the details (org name, user name and password)
5. Click next
6. It failed 

Error log as follows 

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12/11/2019 12:18:29 PM  Initialize CRM connection Started - AuthType: Office365
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	12/11/2019 12:18:29 PM  Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	12/11/2019 12:18:29 PM  DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12/11/2019 12:18:29 PM  DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12/11/2019 12:18:31 PM  DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:01.9767817
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12/11/2019 12:18:31 PM  DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	12/11/2019 12:18:37 PM  Invalid Login Information : An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 12/11/2019
Time	: 12:18:37 PM
Error	: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederatedTokenWithOrgIdForCRM(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 12/11/2019
Time	: 12:18:37 PM
Error	: Authentication Failure
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	12/11/2019 12:18:37 PM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	12/11/2019 12:18:37 PM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 12/11/2019
Time	: 12:18:37 PM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

Please note I have checked my credentials , and with the same credentials, I am able to log into CRM dynamics, I am also System administrator for the org

![Error Snpshot](https://user-images.githubusercontent.com/58763455/70598642-4d973b80-1c11-11ea-990b-e4ed02744a01.PNG)
![Configuration](https://user-images.githubusercontent.com/58763455/70598726-79b2bc80-1c11-11ea-80b6-8b2cae08c7c8.PNG)

**Comment by MscrmTools** [comment]
Is your local active directory federated with office 365?

**Comment by ansabha** [comment]
This is AAD . I don't have federated active directory. It is only azure active directory

**Comment by ansabha** [comment]
Can anybody help me on this.

**Comment by MscrmTools** [comment]
Never had any issue for classic connection if nothing specific from a security standpoint is enabled (like MFA or local AD federation).

So I don’t see how to help... or come chat with me on Gitter.im privately so that I can try to connect myself with your credentials

**Comment by RichieRoxx** [comment]
strange, I have this now as well for several customers that I work with, actually all i tried... :(

**Comment by RichieRoxx** [comment]
also it strangely started to work again out of a sudden...

**Comment by sk00t3r** [comment]
Myself and some others are getting this same error. We do use MFA, however one co-worker has no issue connecting. Any suggestions?

**Comment by MscrmTools** [comment]
unfortunately not... if it works for some users or some orgs and not for others, then XTB cannot be the root cause...

**Comment by oerzzz** [comment]
what a pitty this thread is closed.
The issue arised in my company today. We are trying to figure out what changed.

**Comment by MscrmTools** [comment]
If the issue is new to you, then XrmToolBox is not the cause.
Try to connect with plugin registration tool to see if it works or not

**Comment by NotITperson** [comment]
I haven't used the XrmToolBox in possibly 12 months, but now need to make a change to our site map - I am getting this issue (which I previously did not).  Was there a solution?

**Comment by MscrmTools** [comment]
Ok so it could be related to a change on Microsoft side.
I faced the same issue and was able to connect using MFA connection type (even if MFA is not used).
But you need an appid and a redirect url. 
You can use developer ones as stated in this CRM tip of the day: https://crmtipoftheday.com/1339/the-easiest-cds-dynamics-365-crm-connection-ever/

**Comment by oerzzz** [comment]
The newest version seems to be able to deal with MFA, which was the core issue for me.
The issue occurred after IT implemented some stricter rules.
Now it's working for all of us, in and outside the organisation, with and without MFA.
Not sure that helps, though.

**Comment by agsiddiqui12** [comment]
I got exactly the same error but in my case it was very misleading. My password was due to be changed and that's why it was giving me this error. I tried logging on to Plugin Registration tool (D365 SDK one) and it asked me to change my password which I changed and it worked immediately after that.
