### ISSUE TITLE
Error sending feedback

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#917]
Used the feedback menu option for a tool, and got this:
![image](https://user-images.githubusercontent.com/2572253/73530777-65bd5700-4419-11ea-8ec6-462a41755cf5.png)

Related to #905.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at XrmToolBox.New.NewForm.GetGithubBaseUrl(String page)
   at XrmToolBox.New.NewForm.githubPluginMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

---
- Deployment: Online
- DB Version: 9.1.0.12056
- XTB Version: 1.2020.131.378

**Comment by rappen** [comment]
Cannot repro now, but perhaps worth investigating possible null errors in the code...

**Comment by MscrmTools** [comment]
Ok i will double check

**Comment by MscrmTools** [comment]
Here is the code. Cannot see any NullReference possibility

``` 
private string GetGithubBaseUrl(string page)
{
    var plugin = (IGitHubPlugin)((PluginForm)dpMain.ActiveContent).Control;
    return $"https://github.com/{plugin.UserName}/{plugin.RepositoryName}/{page}";
}
```

**Comment by rappen** [comment]
Agreed.
And it may be related to my strange setup where LCG and UDG are both just shells with PluginDescription, and both reference LDG.UDG.Common...
Leave this open for "a while" to see if it occurs again?

**Comment by MscrmTools** [comment]
sure
