### ISSUE TITLE
Cannot connect to instances or create new connections using SDK Login Control

### ISSUE THREAD

**Issue by fx-oc** [MscrmTools/XrmToolBox#927]
After upgrading to v1.2020.2.37, I cannot connect to any of my previous connections. When attempting to recreate said connections via SDK Login Controls, I get the error in the image (used fxoc in lieu of my actual username)

![image](https://user-images.githubusercontent.com/61299205/74992974-ba467600-549d-11ea-9193-9f560260955c.png)

The error logs give me this:

> Source	: Microsoft.Xrm.Tooling.CrmConnectControl
Method	: QueryOnlineServerList
Date	: 21/02/2020
Time	: 11:29:43 AM
Error	: Method not found: 'System.String Microsoft.Xrm.Sdk.Discovery.OrganizationDetail.get_Geo()'.
Stack Trace	: at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOnlineServerList(ObservableCollection`1 svrs, OrganizationDetailCollection col, ClientCredentials liveCreds, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)

Same result if I set region to Don't Know instead of Oceania.

Attempt to connect via Connection Wizard will give this error after entering Username / Password:

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

> ************** Exception Text **************
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.RijndaelManaged..ctor()
   at McTools.Xrm.Connection.CryptoManager.Encrypt(String plainText, String passPhrase, String saltValue, String hashAlgorithm, Int32 passwordIterations, String initVector, Int32 keySize)
   at McTools.Xrm.Connection.ConnectionDetail.SetPassword(String password, Boolean isEncrypted)
   at McTools.Xrm.Connection.WinForms.ConnectionWizard2.btnNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MscrmTools** [comment]
For this one, you have old DDK assemblies in your GAC. Please remove them
