### ISSUE TITLE
Missing tool icon breaks tool auto update

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#937]
If a tool has an update and the tool description has a missing (or invalid?) image reference, the tool auto updater breaks with Server Error 500 when you try to run the tool.

Trace:
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Windows.Forms.PictureBox.Load()
   at XrmToolBox.Forms.NewPluginVersion..ctor(XtbPlugin plugin)
   at XrmToolBox.New.NewForm.PluginsForm_OpenPluginRequested(Object sender, PluginEventArgs e)
   at XrmToolBox.Extensibility.UserControls.LargePluginModel.MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Ref issue for PRT: https://github.com/Innofactor/PluginRegistration/issues/67
These combined issues make PRT break badly for everyone not running latest version of PRT.

---
- Deployment: Online
- DB Version: 9.1.0.15943
- XTB Version: 1.2020.2.37

**Comment by MscrmTools** [comment]
Thanks for reporting @rappen, I will fix this.
I have a release underway so it's appropriate time to fix it!
