### ISSUE TITLE
Error when creating a new connection with connectionstring

### ISSUE THREAD

**Issue by scubaracer** [MscrmTools/XrmToolBox#948]
connection string was with client and secret
When pressing the next button you get:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at McTools.Xrm.Connection.ConnectionDetail.get_UseOnline()
   at McTools.Xrm.Connection.WinForms.CustomControls.ConnectionLoadingControl..ctor(ConnectionDetail detail)
   at McTools.Xrm.Connection.WinForms.ConnectionWizard2.DisplayControl[T]()
   at McTools.Xrm.Connection.WinForms.ConnectionWizard2.btnNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---
- XTB Version: 1.2020.4.38

**Comment by MscrmTools** [comment]
Hi, Thank you for reporting. 
This is a known issue already fixed that will be deployed in next release
